bitSet.h File Reference
#include `stdio.h`
#include `stdlib.h`
#include `string.h`
Data Structures
struct bitSet_t
struct bitGraph_t
Defines
#define BSBITSIZE (sizeof(bit_t) * 8)
Get the size of a bit_t, which is an unsigned int.
#define BSMASK(y) (((bit_t) 1) << y % BSBITSIZE)
#define BITSLOT(y) (y / BSBITSIZE)
#define BSSET(x, y) (x[BITSLOT(y)] |= BSMASK(y))
Sets the y'th bit in x (a bitset_t) to be true using bitwise operators.
#define BSCLEAR(x, y) (x[BITSLOT(y)] &= ~BSMASK(y))
Sets the y'th bit in x (a bitset_t) to be false using bitwise operators.
#define BSTEST(x, y) (x[BITSLOT(y)] & BSMASK(y))
Tests whether the y'th bit in x (a bitset_t) is true.
#define BSNUMSLOTS(n) ((n + BSBITSIZE - 1) / BSBITSIZE)
#define BSUNION(x, y) ((x)|(y))
Performs a union operation on two bit_t's with bitwise operators.
#define BSINTERSECTION(x, y) ((x)&(y))
Performs an intersection operation on two bit_t's with bitwise operators.
Typedefs
typedef unsigned int bit_t
Functions
bit_t * newBitArray (int bytes)
bitSet_t * newBitSet (int size)
int setTrue (bitSet_t *s1, int x)
int setFalse (bitSet_t *s1, int x)
int bitSetDifference (bitSet_t *s1, bitSet_t *s2, bitSet_t *s3)
int bitSet3WayDifference (bitSet_t *s1, bitSet_t *s2, bitSet_t *s3, bitSet_t *s4)
int bitSetSum (bitSet_t *s1, bitSet_t *s2, bitSet_t *s3)
int flipBits (bitSet_t *s1)
int fillSet (bitSet_t *s1)
int emptySet (bitSet_t *s1)
int checkBit (bitSet_t *s1, int x)
int copyBitGraph (bitGraph_t *bg1, bitGraph_t *bg2)
int copySet (bitSet_t *s1, bitSet_t *s2)
int deleteBitSet (bitSet_t *s1)
int bitSetUnion (bitSet_t *s1, bitSet_t *s2, bitSet_t *s3)
int bitSetIntersection (bitSet_t *s1, bitSet_t *s2, bitSet_t *s3)
int bitSet3WayIntersection (bitSet_t *s1, bitSet_t *s2, bitSet_t *s3, bitSet_t *s4)
int countSet (bitSet_t *s1)
int fillBitGraph (bitGraph_t *bg1)
int emptyBitGraph (bitGraph_t *bg1)
int printBitSet (bitSet_t *s1)
int nextBitBitSet (bitSet_t *s1, int start)
int countBitGraphNonZero (bitGraph_t *bg)
int printBinaryBitSet (bitSet_t *s1)
int bitGraphSetTrue (bitGraph_t *bg, int x, int y)
int bitGraphSetTrueSym (bitGraph_t *bg, int x, int y)
int bitGraphSetTrueDiagonal (bitGraph_t *bg)
int bitGraphSetFalseDiagonal (bitGraph_t *bg)
int printBitGraph (bitGraph_t *bg)
bitGraph_t * newBitGraph (int size)
int deleteBitGraph (bitGraph_t *bg)
int bitGraphRowUnion (bitGraph_t *bg, int row1, int row2, bitSet_t *s1)
int bitGraphRowIntersection (bitGraph_t *bg, int row1, int row2, bitSet_t *s1)
int bitGraphCheckBit (bitGraph_t *bg, int x, int y)
int bitGraphSetFalseSym (bitGraph_t *bg, int x, int y)
int bitGraphSetFalse (bitGraph_t *bg, int x, int y)
int emptyBitGraphRow (bitGraph_t *bg, int row)
int maskBitGraph (bitGraph_t *bg1, bitSet_t *bs)
Detailed Description
This file provides declarations and definitions for a bit set object. The functions declared here are defined in bitSet.c.
Definition in file bitSet.h.
Define Documentation
#define BITSLOT(y) (y / BSBITSIZE)
Finds which bit_t, or `slot`, in a bitset_t the y'th bit belongs to. Also used for testing single bits.
Definition at line 71 of file bitSet.h.
Referenced by nextBitBitSet().
#define BSBITSIZE (sizeof(bit_t) * 8)
Definition at line 63 of file bitSet.h.
Referenced by nextBitBitSet().
#define BSCLEAR(x, y) (x[BITSLOT(y)] &= ~BSMASK(y))
Definition at line 77 of file bitSet.h.
Referenced by setFalse().
#define BSINTERSECTION(x, y) ((x)&(y))
Definition at line 93 of file bitSet.h.
Referenced by bitSet3WayIntersection(), and bitSetIntersection().
#define BSMASK(y) (((bit_t) 1) << y % BSBITSIZE)
Uses bit operations to make a mask the size of a bit_t with the y'th bit true and all other bits false. Used for testing a single bit.
Definition at line 67 of file bitSet.h.
#define BSNUMSLOTS(n) ((n + BSBITSIZE - 1) / BSBITSIZE)
Finds the total number of bit_t's (`slot`s) that are necessary for a bitset of length n. Uses integer division and supplements by BSBITSIZE - 1 to make sure that for slots that are less than full, a slot is still allocated, and for slots that are full, no extra slot is allocated.
Definition at line 87 of file bitSet.h.
Referenced by newBitSet().
Definition at line 74 of file bitSet.h.
Referenced by setTrue().
#define BSTEST(x, y) (x[BITSLOT(y)] & BSMASK(y))
Definition at line 80 of file bitSet.h.
Referenced by checkBit(), printBinaryBitSet(), and printBitSet().
#define BSUNION(x, y) ((x)|(y))
Definition at line 90 of file bitSet.h.
Referenced by bitSetUnion().
Typedef Documentation
typedef unsigned int bit_t
a bit_t is the size of an unsigned integer on the current architecture.
Definition at line 15 of file bitSet.h.
Function Documentation
int bitGraphCheckBit (bitGraph_t * bg, int x, int y)
Checks the value of a bit in a bitGraph_t object. Input: a bitGraph_t object, the index of the row of the bitGraph_t with the bit to be checked, the index of the bit in that row that is to be checked. Output: the value of the bit in the bitGraph being checked.
Definition at line 599 of file bitSet.c.
References checkBit(), and bitGraph_t::graph.
Referenced by main(), and measureDiagonal().
int bitGraphRowIntersection (bitGraph_t * bg, int row1, int row2, bitSet_t * s1)
Finds the intersection of two rows (bitSets) within a bitGraph_t object. Input: a bitGraph_t object, first row to be compared, second row to be compared, and a bitSet_t to store the intersection results. Output: integer success value of 0 (and an altered destination bitSet_t object with a true value wherever both source bitSets had a true value).
Definition at line 572 of file bitSet.c.
References bitSetIntersection(), and bitGraph_t::graph.
Referenced by getStatMat(), and oldGetStatMat().
int bitGraphRowUnion (bitGraph_t * bg, int row1, int row2, bitSet_t * s1)
Finds the union of two rows (bitSets) within a bitGraph Input: a bitGraph_t object, first row to be compared, second row to be compared, and a bitSet_t to store the union results. Output: integer success value of 0 (and an altered destination bitSet_t object with a true value wherever one or both source bitSets had a true value).
Definition at line 560 of file bitSet.c.
References bitSetUnion(), and bitGraph_t::graph.
int bitGraphSetFalse (bitGraph_t * bg, int x, int y)
Sets a specific bit in a bitGraph false. Input: a bitGraph_t object, the index of the row of the bitGraph_t with the bit be set, the index of the bit in that row that is to be set. Output: integer success value of 0 (and an altered bitGraph_t object).
Definition at line 623 of file bitSet.c.
References bitGraph_t::graph, and setFalse().
int bitGraphSetFalseDiagonal (bitGraph_t * bg)
Sets the main diagonal of a bitGraph false. Input: a bitGraph_t object. Output: integer success value of 0 (and an altered bitGraph_t object).
Definition at line 678 of file bitSet.c.
References bitGraph_t::graph, and setFalse().
Referenced by convolve().
int bitGraphSetFalseSym (bitGraph_t * bg, int x, int y)
Sets a specific bit and its symmetric opposite in a bitGraph false. For instance, given that we wanted to set the 3rd bit in the 5th row false, this would also set the 5th bit in the 3rd row. Input: a bitGraph_t object, the index of the row of the bitGraph with the bit be set, the index of the bit in that row that is to be set. Output: integer success value of 0 (and an altered bitGraph_t object).
Definition at line 637 of file bitSet.c.
References bitGraph_t::graph, and setFalse().
int bitGraphSetTrue (bitGraph_t * bg, int x, int y)
Sets a specific bit in a bitGraph true. Input: a bitGraph_t object, the index of the row of the bitGraph_t with the bit be set, the index of the bit in that row that is to be set. Output: integer success value of 0 (and an altered bitGraph_t object).
Definition at line 611 of file bitSet.c.
References bitGraph_t::graph, and setTrue().
int bitGraphSetTrueDiagonal (bitGraph_t * bg)
Sets the main diagonal of a bitGraph true. Input: a bitGraph_t object. Output: integer success value of 0 (and an altered bitGraph_t object).
Definition at line 664 of file bitSet.c.
References bitGraph_t::graph, and setTrue().
int bitGraphSetTrueSym (bitGraph_t * bg, int x, int y)
Sets a specific bit and its symmetric opposite in a bitGraph true. For instance, given that we wanted to set the 3rd bit in the 5th row true, this would also set the 5th bit in the 3rd row. Input: a bitGraph, the index of the row of the bitGraph with the bit be set, the index of the bit in that row that is to be set. Output: integer success value of 0 (and an altered bitGraph_t object).
Definition at line 652 of file bitSet.c.
References bitGraph_t::graph, and setTrue().
Referenced by alignWordsMat_bit(), main(), and realComparison().
int bitSet3WayDifference (bitSet_t * s1, bitSet_t * s2, bitSet_t * s3, bitSet_t * s4)
int bitSet3WayIntersection (bitSet_t * s1, bitSet_t * s2, bitSet_t * s3, bitSet_t * s4)
Finds the intersection of 3 bitSets. Input: First bitSet to be intersected, second bitset to be intersected. third bitSet to be intersected, a bitSet to store the result of the intersection. Output: Integer success value of 0 (and an altered destination bitSet_t object with a true where all three source bitSets had a true.)
Definition at line 304 of file bitSet.c.
References BSINTERSECTION, bitSet_t::slots, and bitSet_t::tf.
int bitSetDifference (bitSet_t * s1, bitSet_t * s2, bitSet_t * s3)
Locates all differences between two bitSets. The result bitSet contains a true at a given bit if the two source bitSets differ at that bit. Input: first bit set to be compared, second bit set to be compared. third bit set to store the results Output: integer success value of 0 (and an altered destination bitSet_t object with a true where the two source bit sets differed).
Definition at line 237 of file bitSet.c.
References bitSet_t::slots, and bitSet_t::tf.
int bitSetIntersection (bitSet_t * s1, bitSet_t * s2, bitSet_t * s3)
Finds the intersection of two bitsets. Input: First bitSet to be intersected, second bitSet to be intersected. a bitSet to store the result of the intersection. Output: Integer success value of 0 (and an altered destination bitSet_t object. with a true where both source bitSets had a true).
Definition at line 278 of file bitSet.c.
References BSINTERSECTION, bitSet_t::slots, and bitSet_t::tf.
Referenced by bitGraphRowIntersection(), findCliques(), and maskBitGraph().
int bitSetSum (bitSet_t * s1, bitSet_t * s2, bitSet_t * s3)
Adds two bitSet_t objects together. Currently unknown functionality, not used in existing code.
Definition at line 256 of file bitSet.c.
References bitSet_t::slots, and bitSet_t::tf.
int bitSetUnion (bitSet_t * s1, bitSet_t * s2, bitSet_t * s3)
Finds the union of two bitSets Input: first bit set for the union, second bit set for the union. a bit set in which to store the results Output: an integer success value of 0 (and an altered third bitSet_t with the results of the union.
Definition at line 175 of file bitSet.c.
References BSUNION, bitSet_t::slots, and bitSet_t::tf.
Referenced by bitGraphRowUnion(), and singleLinkage().
int checkBit (bitSet_t * s1, int x)
Finds the value of a specific bit in a bitSet. Input: a bitSet, the number of the bit being queried. Output: the value of the bit being queried (1 or 0).
Definition at line 143 of file bitSet.c.
References BSTEST, and bitSet_t::tf.
Referenced by bitGraphCheckBit(), findCliques(), getStatMat(), maskBitGraph(), nextBitBitSet(), singleLinkage(), and wholeRoundConv().
int copyBitGraph (bitGraph_t * bg1, bitGraph_t * bg2)
Copies the true/false contents of one bit graph into an existing bit graph. Both bit graphs must be the same size, and each corresponding bit set between the two bit graphs must be the same size. Input: source bit graph, destination bitGraph_t object. Output: integer success value of 0 (and an altered destination bit graph).
Definition at line 215 of file bitSet.c.
References copySet(), bitGraph_t::graph, and bitGraph_t::size.
int copySet (bitSet_t * s1, bitSet_t * s2)
Copies the true/false contents of one bit set into an existing bit set. Both bit sets must be the same size. Input: source bit set, destination bitSet_t object. Output: integer success value of 0 (and an altered destination bitset.
Definition at line 195 of file bitSet.c.
References bitSet_t::slots, and bitSet_t::tf.
Referenced by copyBitGraph(), filterGraph(), and singleLinkage().
int countBitGraphNonZero (bitGraph_t * bg)
Counts the number of true (non-zero) values in a bitGraph_t object. Input: a bitGraph_t object. Output: the integer number of true (non-zero) values in the bitGraph_t object.
Definition at line 511 of file bitSet.c.
References countSet(), and bitGraph_t::graph.
int countSet (bitSet_t * s1)
Counts the number of true values in a bitSet. Input: a bitSet_t object. Output: number of true values in that bitSet_t object.
Definition at line 413 of file bitSet.c.
References bitcount32_precomp(), and bitSet_t::tf.
Referenced by bitSetToCSet(), countBitGraphNonZero(), filterGraph(), filterIter(), findCliques(), getStatMat(), oldGetStatMat(), printBitSet(), singleLinkage(), and wholeCliqueConv().
int deleteBitGraph (bitGraph_t * bg)
Deletes a bitGraph_t object from memory. Input: a bitGraph_t object to be deleted. Output: integer success value from 0 (and deletion of a bitGraph_t object).
Definition at line 799 of file bitSet.c.
References deleteBitSet(), and bitGraph_t::graph.
Referenced by main().
int deleteBitSet (bitSet_t * s1)
Performs memory management for the deletion of a bitSet_t structure. Input: a bitSet_t object. Output: integer success value of 1.
Definition at line 154 of file bitSet.c.
References bitSet_t::tf.
Referenced by convolve(), deleteBitGraph(), filterGraph(), findCliques(), getStatMat(), oldGetStatMat(), wholeCliqueConv(), and wholeRoundConv().
int emptyBitGraph (bitGraph_t * bg1)
Sets all bits in the bitGraph_t object to false. Input: a bitGraph_t object. Output: integer success value of 0 (and a bitGraph_t with all false bits).
Definition at line 744 of file bitSet.c.
References emptySet(), and bitGraph_t::graph.
int emptyBitGraphRow (bitGraph_t * bg, int row)
Sets all bits in a bitGraph_t row (a bitSet_t object) false. Input: a bitGraph, a row in the bitGraph_t object to be emptied. Output: integer success value of 0 (and an altered bitGraph_t object).
Definition at line 788 of file bitSet.c.
References emptySet(), and bitGraph_t::graph.
int emptySet (bitSet_t * s1)
Sets all values in a bitSet to false. Input: a bitSet_t object. Output: integer success value of 1.
Definition at line 131 of file bitSet.c.
References bitSet_t::bytes, and bitSet_t::tf.
Referenced by emptyBitGraph(), emptyBitGraphRow(), filterGraph(), filterIter(), maskBitGraph(), pruneBitGraph(), and searchMemsWithList().
int fillBitGraph (bitGraph_t * bg1)
Sets all bits in the bitGraph_t object to true. Input: a bitGraph_t object. Output: integer success value of 0 (and a bitGraph_t object with all true bits).
Definition at line 730 of file bitSet.c.
References fillSet(), and bitGraph_t::graph.
int fillSet (bitSet_t * s1)
Sets all values in a bitSet to true. Input: a bitSet. Output: integer success value of 1.
Definition at line 119 of file bitSet.c.
References bitSet_t::bytes, and bitSet_t::tf.
Referenced by convolve(), fillBitGraph(), and wholeRoundConv().
int flipBits (bitSet_t * s1)
Inverts all values in a bitSet, making all trues false and all falses true. Input: a bitSet. Output: integer success value of 1.
Definition at line 105 of file bitSet.c.
References bitSet_t::tf.
int maskBitGraph (bitGraph_t * bg1, bitSet_t * bs)
Makes a bitGraph contain only true bits according to the bitmask given. Only locations with the row and column both true in the bitmask can be true if they were initially true. If they were false, they remain false. If the location does not have both the row and the column in the bitmask, it is made false. Note, this is not currently used in Gemoda. Input: a bitGraph, a mask in the form of a bitSet_t object. Output: integer success value of 0 (and an altered bitGraph_t object).
Definition at line 712 of file bitSet.c.
References bitSetIntersection(), checkBit(), emptySet(), and bitGraph_t::graph.
bit_t* newBitArray (int bytes)
Creates a bit array for use in high-throughput intersections/unions. Input: desired size of bit array in byte. Output: a new bit array in bit_t forma. Note: this should not be called directly; see newBitSet.
Definition at line 18 of file bitSet.c.
Referenced by newBitSet().
bitGraph_t* newBitGraph (int size)
Creates a bitGraph_t data structure. Input: the size of the (square) bitGraph_t object. Output: a new bitGraph_t data structure.
Definition at line 758 of file bitSet.c.
References bitGraph_t::graph, newBitSet(), and bitGraph_t::size.
Referenced by alignWordsMat_bit(), main(), and realComparison().
bitSet_t* newBitSet (int size)
Creates a bitSet data structure that contains a bit array and information about that bit array that is necessary for quick and efficient access of the array. Input: the desired length of the bit array. Output: a bitSet data structure.
Definition at line 40 of file bitSet.c.
References BSNUMSLOTS, bitSet_t::bytes, bitSet_t::max, newBitArray(), bitSet_t::slots, and bitSet_t::tf.
Referenced by convolve(), filterGraph(), findCliques(), getStatMat(), newBitGraph(), oldGetStatMat(), wholeCliqueConv(), and wholeRoundConv().
int nextBitBitSet (bitSet_t * s1, int start)
Finds the index of the first non-zero bit at-or-after start. Input: a bitSet_t to be searched, the index of the start bit. Output: the index of the first non-zero bit at-or-after start.
Definition at line 452 of file bitSet.c.
References BITSLOT, BSBITSIZE, checkBit(), bitSet_t::max, bitSet_t::slots, and bitSet_t::tf.
Referenced by bitSetToCSet(), filterIter(), findCliques(), getStatMat(), pruneBitGraph(), and singleLinkage().
int printBinaryBitSet (bitSet_t * s1)
Prints a representation of a bitSet_t structure as a string of 1's and 0's. Input: a bitSet_t object to be printed. Output: integer success value of 0 (and the stdout text described above).
Definition at line 584 of file bitSet.c.
References BSTEST, and bitSet_t::tf.
Referenced by printBitGraph().
int printBitGraph (bitGraph_t * bg)
Prints a representation of a bitGraph using printBinaryBitSet. Input: a bitGraph_t object. Output: integer success value of 0 (and stdout text as described above).
Definition at line 692 of file bitSet.c.
References bitGraph_t::graph, and printBinaryBitSet().
int printBitSet (bitSet_t * s1)
Prints a representation of a bitSet_t data structure. Input: a bitSet_t to be displayed. Output: integer success value of 0 (and the stdout text described above).
Definition at line 527 of file bitSet.c.
References BSTEST, and countSet().
int setFalse (bitSet_t * s1, int x)
Sets a specific bit in a bitSet as false. Input: a bitSet, the number of the bit to be set as false. Output: integer success value of 1.
Definition at line 84 of file bitSet.c.
References BSCLEAR, bitSet_t::max, and bitSet_t::tf.
Referenced by bitGraphSetFalse(), bitGraphSetFalseDiagonal(), bitGraphSetFalseSym(), filterIter(), findCliques(), singleCliqueConv(), and singleLinkage().
int setTrue (bitSet_t * s1, int x)
Sets a specific bit in a bitSet as true. Input: a bitSet, the number of the bit to be set as true. Output: integer success value of 1.
Definition at line 63 of file bitSet.c.
References BSSET, bitSet_t::max, and bitSet_t::tf.
Referenced by bitGraphSetTrue(), bitGraphSetTrueDiagonal(), bitGraphSetTrueSym(), filterIter(), findCliques(), and setStackTrue().