bitSet.c File Reference
#include `errno.h`
#include `bitSet.h`
Functions
bit_t * newBitArray (int bytes)
bitSet_t * newBitSet (int size)
int setTrue (bitSet_t *s1, int x)
int setFalse (bitSet_t *s1, int x)
int flipBits (bitSet_t *s1)
int fillSet (bitSet_t *s1)
int emptySet (bitSet_t *s1)
int checkBit (bitSet_t *s1, int x)
int deleteBitSet (bitSet_t *s1)
int bitSetUnion (bitSet_t *s1, bitSet_t *s2, bitSet_t *s3)
int copySet (bitSet_t *s1, bitSet_t *s2)
int copyBitGraph (bitGraph_t *bg1, bitGraph_t *bg2)
int bitSetDifference (bitSet_t *s1, bitSet_t *s2, bitSet_t *s3)
int bitSetSum (bitSet_t *s1, bitSet_t *s2, bitSet_t *s3)
int bitSetIntersection (bitSet_t *s1, bitSet_t *s2, bitSet_t *s3)
int bitSet3WayIntersection (bitSet_t *s1, bitSet_t *s2, bitSet_t *s3, bitSet_t *s4)
int bitcount32 (unsigned int n)
int bitcount32_precomp (unsigned int n)
int bitcount64 (unsigned int n)
int countSet (bitSet_t *s1)
int nextBitBitSet (bitSet_t *s1, int start)
int countBitGraphNonZero (bitGraph_t *bg)
int printBitSet (bitSet_t *s1)
int bitGraphRowUnion (bitGraph_t *bg, int row1, int row2, bitSet_t *s1)
int bitGraphRowIntersection (bitGraph_t *bg, int row1, int row2, bitSet_t *s1)
int printBinaryBitSet (bitSet_t *s1)
int bitGraphCheckBit (bitGraph_t *bg, int x, int y)
int bitGraphSetTrue (bitGraph_t *bg, int x, int y)
int bitGraphSetFalse (bitGraph_t *bg, int x, int y)
int bitGraphSetFalseSym (bitGraph_t *bg, int x, int y)
int bitGraphSetTrueSym (bitGraph_t *bg, int x, int y)
int bitGraphSetTrueDiagonal (bitGraph_t *bg)
int bitGraphSetFalseDiagonal (bitGraph_t *bg)
int printBitGraph (bitGraph_t *bg)
int maskBitGraph (bitGraph_t *bg1, bitSet_t *bs)
int fillBitGraph (bitGraph_t *bg1)
int emptyBitGraph (bitGraph_t *bg1)
bitGraph_t * newBitGraph (int size)
int emptyBitGraphRow (bitGraph_t *bg, int row)
int deleteBitGraph (bitGraph_t *bg)
Detailed Description
This file defines functions for handling bit sets and bit graphs.
Definition in file bitSet.c.
Function Documentation
int bitcount32 (unsigned int n)
Attempt at a fast way of counting how many true values are in a given bitSet_t. Currently deprecated, using precompiled version instead.
Definition at line 351 of file bitSet.c.
352 {
353   /*
354      works for 32-bit numbers only 
355    */
356   /*
357      fix last line for 64-bit numbers 
358    */
359 
360   register unsigned int tmp;
361 
362   tmp = n - ((n >> 1) & 033333333333) - ((n >> 2) & 011111111111);
363   return ((tmp + (tmp >> 3)) & 030707070707) % 63;
364 }
int bitcount32_precomp (unsigned int n)
Uses bits_in_char data structure to determine the number of true bits in a 32-bit int in an efficient manner. Input: 32-bit int (equal to one slot in the bitSet). Output: number of true bits in the input integer.
Definition at line 396 of file bitSet.c.
Referenced by countSet().
397 {
398   // works only for 32-bit ints
399 
400   return bits_in_char[n & 0xffu]
401     + bits_in_char[(n >> 8) & 0xffu]
402     + bits_in_char[(n >> 16) & 0xffu] + bits_in_char[(n >> 24) & 0xffu];
403 }
int bitcount64 (unsigned int n)
Currently there is no support for 64-bit architectures.
Definition at line 420 of file bitSet.c.
421 {
422   n = PCCOUNT (n, 0);
423   n = PCCOUNT (n, 1);
424   n = PCCOUNT (n, 2);
425   n = PCCOUNT (n, 3);
426   n = PCCOUNT (n, 4);
427   n = PCCOUNT (n, 5);       // for 64-bit integers 
428   return n;
429 }
int bitGraphCheckBit (bitGraph_t * bg, int x, int y)
Checks the value of a bit in a bitGraph_t object. Input: a bitGraph_t object, the index of the row of the bitGraph_t with the bit to be checked, the index of the bit in that row that is to be checked. Output: the value of the bit in the bitGraph being checked.
Definition at line 628 of file bitSet.c.
References checkBit(), and bitGraph_t::graph.
Referenced by main(), and measureDiagonal().
629 {
630   return checkBit (bg->graph[x], y);
631 }
int bitGraphRowIntersection (bitGraph_t * bg, int row1, int row2, bitSet_t * s1)
Finds the intersection of two rows (bitSets) within a bitGraph_t object. Input: a bitGraph_t object, first row to be compared, second row to be compared, and a bitSet_t to store the intersection results. Output: integer success value of 0 (and an altered destination bitSet_t object with a true value wherever both source bitSets had a true value).
Definition at line 598 of file bitSet.c.
References bitSetIntersection(), and bitGraph_t::graph.
Referenced by getStatMat(), and oldGetStatMat().
599 {
600   bitSetIntersection (bg->graph[row1], bg->graph[row2], s1);
601   return 0;
602 }
int bitGraphRowUnion (bitGraph_t * bg, int row1, int row2, bitSet_t * s1)
Finds the union of two rows (bitSets) within a bitGraph Input: a bitGraph_t object, first row to be compared, second row to be compared, and a bitSet_t to store the union results. Output: integer success value of 0 (and an altered destination bitSet_t object with a true value wherever one or both source bitSets had a true value).
Definition at line 584 of file bitSet.c.
References bitSetUnion(), and bitGraph_t::graph.
585 {
586   bitSetUnion (bg->graph[row1], bg->graph[row2], s1);
587   return 0;
588 }
int bitGraphSetFalse (bitGraph_t * bg, int x, int y)
Sets a specific bit in a bitGraph false. Input: a bitGraph_t object, the index of the row of the bitGraph_t with the bit be set, the index of the bit in that row that is to be set. Output: integer success value of 0 (and an altered bitGraph_t object).
Definition at line 654 of file bitSet.c.
References bitGraph_t::graph, and setFalse().
655 {
656   setFalse (bg->graph[x], y);
657   return 0;
658 }
int bitGraphSetFalseDiagonal (bitGraph_t * bg)
Sets the main diagonal of a bitGraph false. Input: a bitGraph_t object. Output: integer success value of 0 (and an altered bitGraph_t object).
Definition at line 714 of file bitSet.c.
References bitGraph_t::graph, and setFalse().
Referenced by convolve().
715 {
716   int i;
717   for (i = 0; i < bg->size; i++)
718     {
719       setFalse (bg->graph[i], i);
720     }
721   return 0;
722 }
int bitGraphSetFalseSym (bitGraph_t * bg, int x, int y)
Sets a specific bit and its symmetric opposite in a bitGraph false. For instance, given that we wanted to set the 3rd bit in the 5th row false, this would also set the 5th bit in the 3rd row. Input: a bitGraph_t object, the index of the row of the bitGraph with the bit be set, the index of the bit in that row that is to be set. Output: integer success value of 0 (and an altered bitGraph_t object).
Definition at line 669 of file bitSet.c.
References bitGraph_t::graph, and setFalse().
670 {
671   setFalse (bg->graph[x], y);
672   setFalse (bg->graph[y], x);
673   return 0;
674 }
int bitGraphSetTrue (bitGraph_t * bg, int x, int y)
Sets a specific bit in a bitGraph true. Input: a bitGraph_t object, the index of the row of the bitGraph_t with the bit be set, the index of the bit in that row that is to be set. Output: integer success value of 0 (and an altered bitGraph_t object).
Definition at line 641 of file bitSet.c.
References bitGraph_t::graph, and setTrue().
642 {
643   setTrue (bg->graph[x], y);
644   return 0;
645 }
int bitGraphSetTrueDiagonal (bitGraph_t * bg)
Sets the main diagonal of a bitGraph true. Input: a bitGraph_t object. Output: integer success value of 0 (and an altered bitGraph_t object).
Definition at line 698 of file bitSet.c.
References bitGraph_t::graph, and setTrue().
699 {
700   int i;
701   for (i = 0; i < bg->size; i++)
702     {
703       setTrue (bg->graph[i], i);
704     }
705   return 0;
706 }
int bitGraphSetTrueSym (bitGraph_t * bg, int x, int y)
Sets a specific bit and its symmetric opposite in a bitGraph true. For instance, given that we wanted to set the 3rd bit in the 5th row true, this would also set the 5th bit in the 3rd row. Input: a bitGraph, the index of the row of the bitGraph with the bit be set, the index of the bit in that row that is to be set. Output: integer success value of 0 (and an altered bitGraph_t object).
Definition at line 685 of file bitSet.c.
References bitGraph_t::graph, and setTrue().
Referenced by alignWordsMat_bit(), main(), and realComparison().
686 {
687   setTrue (bg->graph[x], y);
688   setTrue (bg->graph[y], x);
689   return 0;
690 }
int bitSet3WayIntersection (bitSet_t * s1, bitSet_t * s2, bitSet_t * s3, bitSet_t * s4)
Finds the intersection of 3 bitSets. Input: First bitSet to be intersected, second bitset to be intersected. third bitSet to be intersected, a bitSet to store the result of the intersection. Output: Integer success value of 0 (and an altered destination bitSet_t object with a true where all three source bitSets had a true.)
Definition at line 327 of file bitSet.c.
References BSINTERSECTION, bitSet_t::slots, and bitSet_t::tf.
329 {
330   int i;
331   if ((s1->slots != s2->slots) || (s1->slots != s3->slots)
332       || (s1->slots != s4->slots))
333     {
334       fprintf (stderr, "Sets aren't same size!\n");
335       fflush (stderr);
336       exit (0);
337     }
338   for (i = 0; i < s1->slots; i++)
339     {
340       s4->tf[i] = BSINTERSECTION (s1->tf[i], s2->tf[i]);
341       s4->tf[i] = BSINTERSECTION (s3->tf[i], s4->tf[i]);
342     }
343   return 0;
344 }
int bitSetDifference (bitSet_t * s1, bitSet_t * s2, bitSet_t * s3)
Locates all differences between two bitSets. The result bitSet contains a true at a given bit if the two source bitSets differ at that bit. Input: first bit set to be compared, second bit set to be compared. third bit set to store the results Output: integer success value of 0 (and an altered destination bitSet_t object with a true where the two source bit sets differed).
Definition at line 254 of file bitSet.c.
References bitSet_t::slots, and bitSet_t::tf.
255 {
256   int i;
257   if ((s1->slots != s2->slots) || (s1->slots != s3->slots))
258     {
259       fprintf (stderr, "Sets aren't same size!\n");
260       fflush (stderr);
261       exit (0);
262     }
263   for (i = 0; i < s1->slots; i++)
264     {
265       s3->tf[i] = (s1->tf[i] & (~s2->tf[i]));
266     }
267   return 0;
268 }
int bitSetIntersection (bitSet_t * s1, bitSet_t * s2, bitSet_t * s3)
Finds the intersection of two bitsets. Input: First bitSet to be intersected, second bitSet to be intersected. a bitSet to store the result of the intersection. Output: Integer success value of 0 (and an altered destination bitSet_t object. with a true where both source bitSets had a true).
Definition at line 299 of file bitSet.c.
References BSINTERSECTION, bitSet_t::slots, and bitSet_t::tf.
Referenced by bitGraphRowIntersection(), findCliques(), and maskBitGraph().
300 {
301   int i;
302   if ((s1->slots != s2->slots) || (s1->slots != s3->slots))
303     {
304       fprintf (stderr, "Sets aren't same size!\n");
305       fprintf (stderr, "set 1 slots = %d\n", s1->slots);
306       fprintf (stderr, "set 2 slots = %d\n", s2->slots);
307       fprintf (stderr, "set 3 slots = %d\n", s3->slots);
308       fflush (stderr);
309       exit (0);
310     }
311   for (i = 0; i < s1->slots; i++)
312     {
313       s3->tf[i] = BSINTERSECTION (s1->tf[i], s2->tf[i]);
314     }
315   return 0;
316 }
int bitSetSum (bitSet_t * s1, bitSet_t * s2, bitSet_t * s3)
Adds two bitSet_t objects together. Currently unknown functionality, not used in existing code.
Definition at line 275 of file bitSet.c.
References bitSet_t::slots, and bitSet_t::tf.
276 {
277   int i;
278   if ((s1->slots != s2->slots) || (s1->slots != s3->slots))
279     {
280       fprintf (stderr, "Sets aren't same size!\n");
281       fflush (stderr);
282       exit (0);
283     }
284   for (i = 0; i < s1->slots; i++)
285     {
286       s3->tf[i] = (s1->tf[i] + s2->tf[i]);
287     }
288   return 0;
289 }
int bitSetUnion (bitSet_t * s1, bitSet_t * s2, bitSet_t * s3)
Finds the union of two bitSets Input: first bit set for the union, second bit set for the union. a bit set in which to store the results Output: an integer success value of 0 (and an altered third bitSet_t with the results of the union.
Definition at line 182 of file bitSet.c.
References BSUNION, bitSet_t::slots, and bitSet_t::tf.
Referenced by bitGraphRowUnion(), and singleLinkage().
183 {
184   int i;
185   if ((s1->slots != s2->slots) || (s1->slots != s3->slots))
186     {
187       fprintf (stderr, "Sets aren't same size!\n");
188       fflush (stderr);
189       exit (0);
190     }
191   for (i = 0; i < s1->slots; i++)
192     {
193       s3->tf[i] = BSUNION (s1->tf[i], s2->tf[i]);
194     }
195   return 0;
196 }
int checkBit (bitSet_t * s1, int x)
Finds the value of a specific bit in a bitSet. Input: a bitSet, the number of the bit being queried. Output: the value of the bit being queried (1 or 0).
Definition at line 148 of file bitSet.c.
References BSTEST, and bitSet_t::tf.
Referenced by bitGraphCheckBit(), findCliques(), getStatMat(), maskBitGraph(), nextBitBitSet(), singleLinkage(), and wholeRoundConv().
149 {
150   return BSTEST (s1->tf, x);
151 }
int copyBitGraph (bitGraph_t * bg1, bitGraph_t * bg2)
Copies the true/false contents of one bit graph into an existing bit graph. Both bit graphs must be the same size, and each corresponding bit set between the two bit graphs must be the same size. Input: source bit graph, destination bitGraph_t object. Output: integer success value of 0 (and an altered destination bit graph).
Definition at line 229 of file bitSet.c.
References copySet(), bitGraph_t::graph, and bitGraph_t::size.
230 {
231   int i;
232   if (bg1->size != bg2->size)
233     {
234       fprintf (stderr, "Graphs are not the same size!");
235       fflush (stderr);
236       exit (0);
237     }
238   for (i = 0; i < bg1->size; i++)
239     {
240       copySet (bg1->graph[i], bg2->graph[i]);
241     }
242   return 0;
243 }
int copySet (bitSet_t * s1, bitSet_t * s2)
Copies the true/false contents of one bit set into an existing bit set. Both bit sets must be the same size. Input: source bit set, destination bitSet_t object. Output: integer success value of 0 (and an altered destination bitset.
Definition at line 205 of file bitSet.c.
References bitSet_t::slots, and bitSet_t::tf.
Referenced by copyBitGraph(), filterGraph(), and singleLinkage().
206 {
207   int i;
208   if (s1->slots != s2->slots)
209     {
210       fprintf (stderr, "Sets are not the same size!");
211       fflush (stderr);
212       exit (0);
213     }
214   for (i = 0; i < s1->slots; i++)
215     {
216       s2->tf[i] = s1->tf[i];
217     }
218   return 0;
219 }
int countBitGraphNonZero (bitGraph_t * bg)
Counts the number of true (non-zero) values in a bitGraph_t object. Input: a bitGraph_t object. Output: the integer number of true (non-zero) values in the bitGraph_t object.
Definition at line 537 of file bitSet.c.
References countSet(), and bitGraph_t::graph.
538 {
539   int i;
540   int sum = 0;
541   // Iterate over all bitSets in the bitGraph
542   for (i = 0; i < bg->size; i++)
543     {
544       sum += countSet (bg->graph[i]);
545     }
546   return sum;
547 }
int countSet (bitSet_t * s1)
Counts the number of true values in a bitSet. Input: a bitSet_t object. Output: number of true values in that bitSet_t object.
Definition at line 437 of file bitSet.c.
References bitcount32_precomp(), and bitSet_t::tf.
Referenced by bitSetToCSet(), countBitGraphNonZero(), filterGraph(), filterIter(), findCliques(), getStatMat(), oldGetStatMat(), printBitSet(), singleLinkage(), and wholeCliqueConv().
438 {
439   int i;
440   int sum = 0;
441   int (*bitCounter) () = &bitcount32_precomp;
442   // Currently there is no support for 64-bit architectures.
443 
444   if (sizeof (bit_t) * 8 != 32)
445     {
446       fprintf (stderr,
447            "\nSorry, no support for 64-bit architectures just yet! - countSet\n");
448       fflush (stderr);
449       exit (0);
450     }
451 
452   // Just count the number of true bits in each char, and do this for
453   // (num of chars per int) chars.
454   for (i = 0; i < s1->slots; i++)
455     {
456       sum += bitCounter (s1->tf[i]);
457     }
458   return sum;
459 }
int deleteBitGraph (bitGraph_t * bg)
Deletes a bitGraph_t object from memory. Input: a bitGraph_t object to be deleted. Output: integer success value from 0 (and deletion of a bitGraph_t object).
Definition at line 853 of file bitSet.c.
References deleteBitSet(), and bitGraph_t::graph.
Referenced by main().
854 {
855   int i;
856   if (bg != NULL)
857     {
858       if (bg->graph != NULL)
859     {
860       for (i = 0; i < bg->size; i++)
861         {
862           deleteBitSet (bg->graph[i]);
863         }
864       free (bg->graph);
865       bg->graph = NULL;
866     }
867       free (bg);
868       bg = NULL;
869     }
870   return 0;
871 }
int deleteBitSet (bitSet_t * s1)
Performs memory management for the deletion of a bitSet_t structure. Input: a bitSet_t object. Output: integer success value of 1.
Definition at line 159 of file bitSet.c.
References bitSet_t::tf.
Referenced by convolve(), deleteBitGraph(), filterGraph(), findCliques(), getStatMat(), oldGetStatMat(), wholeCliqueConv(), and wholeRoundConv().
160 {
161   if (s1->tf != NULL)
162     {
163       free (s1->tf);
164       s1->tf = NULL;
165     }
166   if (s1 != NULL)
167     {
168       free (s1);
169       s1 = NULL;
170     }
171   return 0;
172 }
int emptyBitGraph (bitGraph_t * bg1)
Sets all bits in the bitGraph_t object to false. Input: a bitGraph_t object. Output: integer success value of 0 (and a bitGraph_t with all false bits).
Definition at line 791 of file bitSet.c.
References emptySet(), and bitGraph_t::graph.
792 {
793   int i;
794   for (i = 0; i < bg1->size; i++)
795     {
796       emptySet (bg1->graph[i]);
797     }
798   return 0;
799 }
int emptyBitGraphRow (bitGraph_t * bg, int row)
Sets all bits in a bitGraph_t row (a bitSet_t object) false. Input: a bitGraph, a row in the bitGraph_t object to be emptied. Output: integer success value of 0 (and an altered bitGraph_t object).
Definition at line 841 of file bitSet.c.
References emptySet(), and bitGraph_t::graph.
842 {
843   emptySet (bg->graph[row]);
844   return 0;
845 }
int emptySet (bitSet_t * s1)
Sets all values in a bitSet to false. Input: a bitSet_t object. Output: integer success value of 1.
Definition at line 136 of file bitSet.c.
References bitSet_t::bytes, and bitSet_t::tf.
Referenced by emptyBitGraph(), emptyBitGraphRow(), filterGraph(), filterIter(), maskBitGraph(), pruneBitGraph(), and searchMemsWithList().
137 {
138   memset (s1->tf, 0, s1->bytes);
139   return 0;
140 }
int fillBitGraph (bitGraph_t * bg1)
Sets all bits in the bitGraph_t object to true. Input: a bitGraph_t object. Output: integer success value of 0 (and a bitGraph_t object with all true bits).
Definition at line 775 of file bitSet.c.
References fillSet(), and bitGraph_t::graph.
776 {
777   int i;
778   for (i = 0; i < bg1->size; i++)
779     {
780       fillSet (bg1->graph[i]);
781     }
782   return 0;
783 }
int fillSet (bitSet_t * s1)
Sets all values in a bitSet to true. Input: a bitSet. Output: integer success value of 1.
Definition at line 124 of file bitSet.c.
References bitSet_t::bytes, and bitSet_t::tf.
Referenced by convolve(), fillBitGraph(), and wholeRoundConv().
125 {
126   memset (s1->tf, ~0, s1->bytes);
127   return 0;
128 }
int flipBits (bitSet_t * s1)
Inverts all values in a bitSet, making all trues false and all falses true. Input: a bitSet. Output: integer success value of 1.
Definition at line 108 of file bitSet.c.
References bitSet_t::tf.
109 {
110   int i;
111   for (i = 0; i < s1->slots; i++)
112     {
113       s1->tf[i] = ~s1->tf[i];
114     }
115   return 0;
116 }
int maskBitGraph (bitGraph_t * bg1, bitSet_t * bs)
Makes a bitGraph contain only true bits according to the bitmask given. Only locations with the row and column both true in the bitmask can be true if they were initially true. If they were false, they remain false. If the location does not have both the row and the column in the bitmask, it is made false. Note, this is not currently used in Gemoda. Input: a bitGraph, a mask in the form of a bitSet_t object. Output: integer success value of 0 (and an altered bitGraph_t object).
Definition at line 752 of file bitSet.c.
References bitSetIntersection(), checkBit(), emptySet(), and bitGraph_t::graph.
753 {
754   int i;
755   for (i = 0; i < bg1->size; i++)
756     {
757       if (checkBit (bs, i))
758     {
759       bitSetIntersection (bg1->graph[i], bs, bg1->graph[i]);
760     }
761       else
762     {
763       emptySet (bg1->graph[i]);
764     }
765     }
766   return 0;
767 }
bit_t* newBitArray (int bytes)
Creates a bit array for use in high-throughput intersections/unions. Input: desired size of bit array in byte. Output: a new bit array in bit_t forma. Note: this should not be called directly; see newBitSet.
Definition at line 20 of file bitSet.c.
Referenced by newBitSet().
21 {
22   bit_t *b = (bit_t *) malloc (bytes);
23   if (b == NULL)
24     {
25       fprintf (stderr, "\nMemory error --- couldn't allocate bitArray!"
26            " - newBitArray\n%s\n", strerror (errno));
27       fflush (stderr);
28       exit (0);
29     }
30   // Set them all false
31   memset (b, 0, bytes);
32   return b;
33 }
bitGraph_t* newBitGraph (int size)
Creates a bitGraph_t data structure. Input: the size of the (square) bitGraph_t object. Output: a new bitGraph_t data structure.
Definition at line 807 of file bitSet.c.
References bitGraph_t::graph, newBitSet(), and bitGraph_t::size.
Referenced by alignWordsMat_bit(), main(), and realComparison().
808 {
809   bitGraph_t *bg = NULL;
810   int i;
811   bg = (bitGraph_t *) malloc (sizeof (bitGraph_t));
812   if (bg == NULL)
813     {
814       fprintf (stderr, "Memory error - Cannot allocate bitGraph - "
815            "newBitGraph\n%s\n", strerror (errno));
816       fflush (stderr);
817       exit (0);
818     }
819   bg->size = size;
820   bg->graph = (bitSet_t **) malloc (size * sizeof (bitSet_t *));
821   if (bg->graph == NULL)
822     {
823       fprintf (stderr, "Memory error - Cannot allocate bitGraphGraph - "
824            "newBitGraph\n%s\n", strerror (errno));
825       fflush (stderr);
826       exit (0);
827     }
828   for (i = 0; i < size; i++)
829     {
830       bg->graph[i] = newBitSet (size);
831     }
832   return bg;
833 }
bitSet_t* newBitSet (int size)
Creates a bitSet data structure that contains a bit array and information about that bit array that is necessary for quick and efficient access of the array. Input: the desired length of the bit array. Output: a bitSet data structure.
Definition at line 43 of file bitSet.c.
References BSNUMSLOTS, bitSet_t::bytes, bitSet_t::max, newBitArray(), bitSet_t::slots, and bitSet_t::tf.
Referenced by convolve(), filterGraph(), findCliques(), getStatMat(), newBitGraph(), oldGetStatMat(), wholeCliqueConv(), and wholeRoundConv().
44 {
45   bitSet_t *s1 = (bitSet_t *) malloc (sizeof (bitSet_t));
46   if (s1 == NULL)
47     {
48       fprintf (stderr, "\nMemory error --- couldn't allocate biSet!"
49            " - newBitSet\n%s\n", strerror (errno));
50       fflush (stderr);
51       exit (0);
52     }
53   // Fill in details about the bitSet, allocate bitSet
54   s1->max = size;
55   s1->slots = BSNUMSLOTS (size);
56   s1->bytes = s1->slots * sizeof (bit_t);
57   s1->tf = newBitArray (s1->bytes);
58   return s1;
59 }
int nextBitBitSet (bitSet_t * s1, int start)
Finds the index of the first non-zero bit at-or-after start. Input: a bitSet_t to be searched, the index of the start bit. Output: the index of the first non-zero bit at-or-after start.
Definition at line 468 of file bitSet.c.
References BITSLOT, BSBITSIZE, checkBit(), bitSet_t::max, and bitSet_t::tf.
Referenced by bitSetToCSet(), filterIter(), findCliques(), getStatMat(), pruneBitGraph(), and singleLinkage().
469 {
470   // slot is our starting slot, the
471   // slot containing bit 'start'
472   int slot = BITSLOT (start);
473   int i;
474   // stop is the bit to stop it --- it is equal to max, and it is
475   // the index of a bit that does NOT belong to the bitset
476   int stop;
477   bit_t bitFalse;
478   memset (&bitFalse, 0, sizeof (bit_t));
479 
480 
481   // s1->max is the number of bits in s1
482   // test to see if we're looking too high
483   if (start >= s1->max)
484     {
485       return -1;
486     }
487   // s1->slots is the number of available slots
488   // skip over empty slots
489   while (slot < s1->slots)
490     {
491       /*
492          printf("w");
493        */
494       if (s1->tf[slot] != bitFalse)
495     {
496       // this slot is not empty
497 
498       // if each slot is, say 32 bits and 
499       // we asked for nextBitBitSet(s1, 5),
500       // then slot 0 will be non-zero.  but,
501       // instead of starting at 0, start at 5!
502       if (BSBITSIZE * slot > start)
503         {
504           // set start to index of first
505           // bit in this slot
506           start = BSBITSIZE * slot;
507         }
508       // set the stop, with a a check against the 'max'
509       // element of the bitSet_t object
510       if (BSBITSIZE * (slot + 1) > s1->max)
511         {
512           stop = s1->max;
513         }
514       else
515         {
516           stop = BSBITSIZE * (slot + 1);
517         }
518       for (i = start; i < stop; i++)
519         {
520           if (checkBit (s1, i))
521         {
522           return i;
523         }
524         }
525     }
526       slot++;
527     }
528   return -1;
529 }
int printBinaryBitSet (bitSet_t * s1)
Prints a representation of a bitSet_t structure as a string of 1's and 0's. Input: a bitSet_t object to be printed. Output: integer success value of 0 (and the stdout text described above).
Definition at line 611 of file bitSet.c.
References BSTEST, and bitSet_t::tf.
Referenced by printBitGraph().
612 {
613   int i;
614   for (i = 0; i < s1->max; i++)
615     {
616       printf ("%d", (BSTEST (s1->tf, i) ? 1 : 0));
617     }
618   return 0;
619 }
int printBitGraph (bitGraph_t * bg)
Prints a representation of a bitGraph using printBinaryBitSet. Input: a bitGraph_t object. Output: integer success value of 0 (and stdout text as described above).
Definition at line 730 of file bitSet.c.
References bitGraph_t::graph, and printBinaryBitSet().
731 {
732   int i;
733   for (i = 0; i < bg->size; i++)
734     {
735       printBinaryBitSet (bg->graph[i]);
736       printf ("\n");
737     }
738   return 0;
739 }
int printBitSet (bitSet_t * s1)
Prints a representation of a bitSet_t data structure. Input: a bitSet_t to be displayed. Output: integer success value of 0 (and the stdout text described above).
Definition at line 555 of file bitSet.c.
References BSTEST, and countSet().
556 {
557   int i;
558   printf ("bitSet (addr = %d; %d members)\n", (int) s1, countSet (s1));
559   printf ("\tmax = %d\n", s1->max);
560   printf ("\tslots = %d\n", s1->slots);
561   printf ("\tbytes = %d\n", s1->bytes);
562   printf ("\tmembers =");
563 
564 
565   for (i = 0; i < s1->max; i++)
566     {
567       if (BSTEST (s1->tf, i))
568     {
569       printf (" %d", i);
570     }
571     }
572   printf ("\n");
573   return 0;
574 }
int setFalse (bitSet_t * s1, int x)
Sets a specific bit in a bitSet as false. Input: a bitSet, the number of the bit to be set as false. Output: integer success value of 1.
Definition at line 85 of file bitSet.c.
References BSCLEAR, bitSet_t::max, and bitSet_t::tf.
Referenced by bitGraphSetFalse(), bitGraphSetFalseDiagonal(), bitGraphSetFalseSym(), filterIter(), findCliques(), singleCliqueConv(), and singleLinkage().
86 {
87   /*
88      if (BSNUMSLOTS(x) > s1->slots) { Conditional changed, 5/25, by MPS: check x against s1->max, 
89      should be safer 
90    */
91   if (x >= s1->max)
92     {
93       fprintf (stderr, "Set isn't large enough! - setFalse\n");
94       fflush (stderr);
95       exit (0);
96     }
97   BSCLEAR (s1->tf, x);
98   return 0;
99 }
int setTrue (bitSet_t * s1, int x)
Sets a specific bit in a bitSet as true. Input: a bitSet, the number of the bit to be set as true. Output: integer success value of 1.
Definition at line 67 of file bitSet.c.
References BSSET, bitSet_t::max, and bitSet_t::tf.
Referenced by bitGraphSetTrue(), bitGraphSetTrueDiagonal(), bitGraphSetTrueSym(), filterIter(), findCliques(), and setStackTrue().
68 {
69   if (x >= s1->max)
70     {
71       fprintf (stderr, "Set isn't large enough! - setTrue\n");
72       fflush (stderr);
73       exit (0);
74     }
75   BSSET (s1->tf, x);
76   return 0;
77 }