convll.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include `bitSet.h`
Data Structures
struct cSet_t
struct cnode
struct mnode
Typedefs
typedef cnode cll_t
typedef mnode mll_t
Functions
cll_t * pushCll (cll_t *head)
cll_t * popCll (cll_t *head)
cll_t * popAllCll (cll_t *head)
int printCll (cll_t *head)
cll_t * initheadCll (cll_t *head, cSet_t *newset)
cll_t * pushcSet (cll_t *head, cSet_t *newset)
cll_t * pushClique (bitSet_t *clique, cll_t *head, int *indexToSeq, int p)
mll_t * pushMemStack (mll_t *head, int cliqueNum)
mll_t * popMemStack (mll_t *head)
mll_t * popWholeMemStack (mll_t *head)
mll_t ** addToStacks (cll_t *node, mll_t **memberStacks)
mll_t ** fillMemberStacks (cll_t *head, mll_t **memberStacks)
mll_t ** emptyMemberStacks (mll_t **memberStacks, int size)
void printMemberStacks (mll_t **memberStacks, int size)
bitSet_t * searchMemsWithList (int *list, int listsize, mll_t **memList, int numOffsets, bitSet_t *queue)
bitSet_t * setStackTrue (mll_t **memList, int i, bitSet_t *queue)
cll_t * singleCliqueConv (cll_t *head, int firstClique, cll_t **firstGuess, int secondClique, cll_t **secondGuess, cll_t *nextPhase, bitSet_t *printStatus, int support)
mll_t * mergeIntersect (cll_t *first, cll_t *second, mll_t *intersection, bitSet_t *printStatus, int *newSupport)
cll_t * pushConvClique (mll_t *clique, cll_t *head)
cSet_t * mllToCSet (mll_t *clique)
cSet_t * bitSetToCSet (bitSet_t *clique)
cll_t * wholeCliqueConv (cll_t *head, cll_t *node, cll_t **firstGuess, mll_t **memList, int numOffsets, cll_t *nextPhase, bitSet_t *printStatus, int support)
cll_t * wholeRoundConv (cll_t **head, mll_t **memList, int numOffsets, int support, int length, cll_t **allCliques)
cll_t * completeConv (cll_t **head, int support, int numOffsets, int minLength, int *indexToSeq, int p)
int printCllPattern (cll_t *node, int length)
int uniqClique (cSet_t *clique, cll_t *head)
cll_t * swapNodecSet (cll_t *head, int node, cSet_t *newClique)
int yankCll (cll_t **head, cll_t *prev, cll_t **curr, cll_t **allCliques, int length)
cll_t * removeSupers (cll_t *head, int node, cSet_t *newClique)
Detailed Description
This header file contains declarations and definitions for dealing with different kinds of sets that are used throughout the convolution stage of Gemoda.
Definition in file convll.h.
Typedef Documentation
typedef struct cnode cll_t
This data structure is a linked list for storing cliques. Each member of the linked list has a set, an ID number, a length (which gives the number of characters in the motif), a pointer to the next member of the linked list, and a floating-point number for storing statistical information.
typedef struct mnode mll_t
This data structure is just a link to list of integers used for bookkeeping during the convolution stage.
Function Documentation
mll_t** addToStacks (cll_t * node, mll_t ** memberStacks)
For one clique, it adds membership for that clique to all of its members' member stacks. Input: a specific clique in a clique linked list, an array of member stacks. Output: the array of updated member stacks.
Definition at line 425 of file convll.c.
References cnode::id, cSet_t::members, pushMemStack(), and cnode::set.
Referenced by fillMemberStacks().
cSet_t* bitSetToCSet (bitSet_t * clique)
Converts a bitSet_t to a cSet_t for the purposes of pushing it onto a linked list of cliques. The bitSet_t data structure is used for massive comparisons during clique-finding but is unwieldy/inefficient when it is known that the structure is sparse. The cSet_t allows for efficient comparison of sparse bitSet_t's. Use this just before pushing a newly-discovered clique onto a clique linked list. Input: a new clique in the form of a bitSet_t. Output: the same clique in the form of a cSet_t.
Definition at line 193 of file convll.c.
References countSet(), cSet_t::members, nextBitBitSet(), and cSet_t::size.
Referenced by pushClique(), and wholeCliqueConv().
cll_t* completeConv (cll_t ** head, int support, int numOffsets, int minLength, int * indexToSeq, int p)
Performs complete convolution given the starting list of cliques. Input: a pointer to the head of the initial clique linked list, the minimum support criterion value, the number of offsets in the sequence set, the minimum length of motifs (which is the length of motifs in the initial clique linked list), the index/Sequence data structure, and the value of the -p flag to prune based on unique sequence occurrences. Output: a linked list of all maximal cliques based on the initial clique linked list.
Definition at line 1267 of file convll.c.
References emptyMemberStacks(), fillMemberStacks(), popAllCll(), pruneCll(), and wholeRoundConv().
Referenced by convolve().
mll_t** emptyMemberStacks (mll_t ** memberStacks, int size)
After we have performed a round of convolution, this `empties` the member stacks by popping all nodes off each member linked list. Input: array of member linked lists, the size of that array (total number of offsets). Output: the array of now-empty member linked lists.
Definition at line 474 of file convll.c.
References popWholeMemStack().
Referenced by completeConv().
mll_t** fillMemberStacks (cll_t * head, mll_t ** memberStacks)
Fills the entire memberStacks data structure by calling addToStacks for each clique in the clique linked list. Input: head of a clique linked list, array of member linked lists. Output: the array of updated member linked lists.
Definition at line 455 of file convll.c.
References addToStacks(), and cnode::next.
Referenced by completeConv().
cll_t* initheadCll (cll_t * head, cSet_t * newset)
Initializes the empty head of a linked list by adding a set to that head. Note: this is only called immediately after pushing onto a cll, because the push always creates a new empty head. This function should not be called by the user; see pushcSet. Input: head of a linked list, pointer to a cSet_t list of clique members. Output: head of a linked list.
Definition at line 156 of file convll.c.
References cnode::set.
Referenced by pushcSet().
mll_t* mergeIntersect (cll_t * first, cll_t * second, mll_t * intersection, bitSet_t * printstatus, int * newSupport)
Convolves two cliques in a non-commutative manner. It finds which members of the first clique are immediately followed by a member in the second clique. Input: pointer to the location in the linked list of the first clique to be convolved, pointer to the location in the linked list of the second clique to be convolved, a member linked list used to store the intersection of the two cliques, the printstatus bitSet, and a pointer to an integer with the support of the clique formed by convolution. Output: a member linked list with the intersection of the two cliques, plus the side effect of that intersection's cardinality being stored in the integer pointed to by newSupport.
Definition at line 671 of file convll.c.
References cSet_t::members, pushMemStack(), cnode::set, and cSet_t::size.
Referenced by singleCliqueConv().
cSet_t* mllToCSet (mll_t * clique)
Turns a member linked list used to store the intersection of two cliques into something more useful: a cSet_t structure. Input: a clique in mll_t form. Output: a clique in cSet_t form.
Definition at line 1022 of file convll.c.
References mnode::cliqueMembership, cSet_t::members, mnode::next, and cSet_t::size.
Referenced by pushConvClique().
cll_t* popAllCll (cll_t * head)
Shortcut function to pop all of the members of a linked list. Input: head of a linked list. Output: head of a now-empty linked list.
Definition at line 101 of file convll.c.
References popCll().
Referenced by completeConv(), and main().
cll_t* popCll (cll_t * head)
Removes the head of the clique linked list, returns the new head of the clique linked list, and frees the memory occupied by the old head. Input: head of a linked list. Output: head of a linked list.
Definition at line 60 of file convll.c.
References cSet_t::members, cnode::next, and cnode::set.
Referenced by popAllCll().
mll_t* popMemStack (mll_t * head)
Pops the head off of a single member linked list. Input: head of a member linked list. Output: the new head of a member linked list after popping one item.
Definition at line 388 of file convll.c.
References mnode::next.
Referenced by popWholeMemStack().
mll_t* popWholeMemStack (mll_t * head)
Pops all items off of a member linked list. Input: head of a member linked list. Output: empty head of a member linked list.
Definition at line 410 of file convll.c.
References popMemStack().
Referenced by emptyMemberStacks(), and singleCliqueConv().
int printCll (cll_t * head)
Prints the members (cliques) of a linked list in the format: id = unique id number of clique within linked list; Length = number of members of clique, if available; Size = length of each member of clique; Members = newline-separated list of members of the clique. Input: head of a linked list. Output: Gives text output, returns (meaningless) exit value.
Definition at line 118 of file convll.c.
References cnode::id, cnode::length, cSet_t::members, cnode::next, cnode::set, and cSet_t::size.
int printCllPattern (cll_t * node, int length)
Prints out the contents of a clique linked list node in this format: support = number of motif occurrences (id = some id number); members = newline-separated list of offsets. Input: a specific node to be output, the length of the motif inside it. Output: text per above, and an integer success value.
Definition at line 1328 of file convll.c.
References cnode::id, cSet_t::members, cnode::set, and cSet_t::size.
void printMemberStacks (mll_t ** memberStacks, int size)
Prints the contents of the member stacks. Input: array of member linked lists, size of that array (total number of offsets). Output: only text output/no return value.
Definition at line 491 of file convll.c.
References mnode::cliqueMembership, and mnode::next.
cll_t* pushClique (bitSet_t * clique, cll_t * head, int * indexToSeq, int p)
Pushes a bitSet onto a clique linked list, performing all necessary manipulations in order to do so. Input: new clique in the form of a bitSet_t, head of a linked list, pointer to the index/sequence number data structure, integer value of the -p flag. Output: head of an updated clique linked list.
Definition at line 314 of file convll.c.
References bitSetToCSet(), checkCliquecSet(), cliquecounter, cSet_t::members, and pushcSet().
Referenced by findCliques(), and singleLinkage().
cll_t* pushCll (cll_t * head)
Pushes a new, empty head onto a linked list of cliques. Note: this should always be followed by a call to initheadCll, as the head pushed on here is empty and will be meaningless without any members. This function should NOT be used by the user; see pushcSet. Input: head of a linked list. Output: head of a linked list.
Definition at line 26 of file convll.c.
References cnode::id, cnode::length, cnode::next, cnode::set, and cnode::stat.
Referenced by pushcSet().
cll_t* pushConvClique (mll_t * clique, cll_t * head)
Pushes a freshly-convolved clique, currently in mll_t form, onto the clique linked list for the next level. Also checks to make sure that the convolved clique is unique, and if it isn't, it takes appropriate action. Input: a convolved clique in mll_t form, the head of a clique linked list for the next level. Output: (potentially new) head of the clique linked list for the next level.
Definition at line 980 of file convll.c.
References cSet_t::members, mllToCSet(), pushcSet(), removeSupers(), swapNodecSet(), and uniqClique().
Referenced by singleCliqueConv().
cll_t* pushcSet (cll_t * head, cSet_t * newset)
Function that pushes the contents of a cSet (set of members of a clique) onto a linked list of cliques. Input: head of a linked list, new clique in the form of a cSet_t. Output: head of a linked list.
Definition at line 174 of file convll.c.
References initheadCll(), and pushCll().
Referenced by pushClique(), and pushConvClique().
mll_t* pushMemStack (mll_t * head, int cliqueNum)
This begins code for the member linked lists. A single one of these linked lists functions somewhat similarly to the clique linked lists, though with less information stored. Functionally, an array of member linked lists is used to access the `inverse` of what is contained in the clique linked lists. That is, we would like to be able to look up the cliques that a given node is a member of, so we have an array of member linked lists of size equal to the number of nodes.
This function pushes a single clique membership onto a node's member stack. Input: the head of a single member linked list, a clique number to be added. Output: the head of a single member linked list.
Definition at line 358 of file convll.c.
References mnode::cliqueMembership, and mnode::next.
Referenced by addToStacks(), and mergeIntersect().
cll_t* removeSupers (cll_t * head, int node, cSet_t * newClique)
This function finds all cliques in a linked list of which the proposed clique is a superset. It starts looking AFTER the first clique which has already been found to be a subset. In some senses, it is just a continuation of the uniqclique function in order to take advantage of the fact that though a proposed clique can only be a subset of one existing next-level clique, it can be a superset of many existing next- level cliques. Input: head of a clique linked list, the id of the first node found to be a subset of the proposed clique, and the proposed clique (in cSet_t form). Output: the head of the clique linked list with all but the first subset (which was passed as an argument) removed. This function is now ready for swapNode to be called.
Definition at line 849 of file convll.c.
References cnode::id, cSet_t::members, cnode::next, cnode::set, and cSet_t::size.
Referenced by pushConvClique().
bitSet_t* searchMemsWithList (int * list, int listsize, mll_t ** memList, int numOffsets, bitSet_t * queue)
Creates one large queue by calling `setStackTrue` for each member of a list of offsets. This then creates the union of clique membership for all offsets in the list being searched. Input: an array of offset numbers, the length of that array, an array of member linked lists, the length of that array (the total number of offsets), and a bitSet_t to store the union/queue. Output: the union/queue in a bitSet_t structure.
Definition at line 540 of file convll.c.
References emptySet(), and setStackTrue().
Referenced by wholeCliqueConv().
bitSet_t* setStackTrue (mll_t ** memList, int i, bitSet_t * queue)
Adds all of the members of a given stack to a `queue` in the form of a bitSet_t data structure. That is, for each clique in the member linked list, it sets the corresponding bit in the bitSet_t true. Input: array of member linked lists, an integer indicating a specific member linked list, and a bitSet_t of length >= the number of cliques in the current clique linked list. Ouput: the updated bitSet_t object.
Definition at line 516 of file convll.c.
References mnode::cliqueMembership, mnode::next, and setTrue().
Referenced by searchMemsWithList().
cll_t* singleCliqueConv (cll_t * head, int firstClique, cll_t ** firstGuess, int secondClique, cll_t ** secondGuess, cll_t * nextPhase, bitSet_t * printStatus, int support)
Convolves one single clique against one other single clique. Note that this is non-commutative, so exchanging firstClique and secondClique will not give the same results. The `guess` pointers keep the location of the previous clique in the linked list so that we don't have to search the linked list from the beginning/end every time. We exploit our earlier tidiness in that we can reasonably guess that we will monotonically traverse down cliques. Input: head of the current clique linked list, the id number of the first clique, a pointer to a guess at the first clique, the id number of the second clique, a pointer to a guess at the second clique, the head of the clique linked list for the next round of convolution, a bitSet indicating which cliques should be output as maximal, and the minimum support flag. Output: the head of clique linked list for the next round of convolution (which may have changed if the two cliques could be convolved).
Definition at line 580 of file convll.c.
References cnode::id, mergeIntersect(), cnode::next, popWholeMemStack(), pushConvClique(), cnode::set, setFalse(), and cSet_t::size.
Referenced by wholeCliqueConv().
cll_t* swapNodecSet (cll_t * head, int node, cSet_t * newClique)
Swaps out a node in a linked list that has been found to be a subset of a node that is not yet in the list. Input: the head of a clique linked list, a specific node within that linked list that is to be removed, and the new clique that is the superset of the node to be removed (in cSet_t form). Output: the head of the altered clique linked list.
Definition at line 804 of file convll.c.
References cnode::id, cSet_t::members, cnode::next, and cnode::set.
Referenced by pushConvClique().
int uniqClique (cSet_t * cliquecSet, cll_t * head)
Before we push a convolved clique onto the stack for the next level, this function ensures that it is not subsumed by and does not subsume any other clique currently on that stack. Input: a candidate clique for the next level in cSet_t form, and the head of the clique linked list for the next level. Output: an integer indicating the status of the proposed clique with respect to the next level: -1 if the clique is unique, -2 if the clique is a subset/duplicate of an existing clique, or a clique id in the range [0,numcliques) representing the first clique of which the proposed one is a superset. Note that by executing this each time a clique is added to the next level, we ensure that if the new clique is not unique, it can only be a superset or a subset of some other clique; it cannot be both a strictly superset of one and a strictly subset of another. One of those other two cliques would have been identified in previous steps as being super- or sub-sets, so it is impossible for one clique now to be both a super and a subset.
Definition at line 729 of file convll.c.
References cnode::id, cSet_t::members, cnode::next, cnode::set, and cSet_t::size.
Referenced by pushConvClique().
cll_t* wholeCliqueConv (cll_t * head, cll_t * node, cll_t ** firstGuess, mll_t ** memList, int numOffsets, cll_t * nextPhase, bitSet_t * printStatus, int support)
Convolves one single clique against all possible cliques that could possibly be convolved. It does not attempt to convolve all other cliques, but prunes that set by first looking at the offsets that are in the clique, then collecting all of the cliques who have members that are one greater than the offsets in this clique, and then convolving those cliques in a sort of `queue` using the bitSet_t data structure. Input: the head of the clique linked list for the current level, the current node being convolved against in the linked list, the location of the previous node in the form of a pointer to a `guess`, an array of member linked lists, the length of that array, the head of the clique linked list for the next level, a bitSet_t for the printStatus of maximality, and the support criterion. Output: the head of the (possibly modified) clique linked list for the next level.
Definition at line 1081 of file convll.c.
References bitSetToCSet(), countSet(), deleteBitSet(), cnode::id, cSet_t::members, newBitSet(), searchMemsWithList(), cnode::set, singleCliqueConv(), and cSet_t::size.
Referenced by wholeRoundConv().
cll_t* wholeRoundConv (cll_t ** head, mll_t ** memList, int numOffsets, int support, int length, cll_t ** allCliques)
Performs convolution on all cliques in a linked list by repeatedly calling wholeCliqueConv. Input: pointer to the head of a clique linked list for the current level, array of member linked lists, length of that array, minimum support threshold, the current length of motifs, and a pointer to a linked list containing all cliques that will be printed out. Output: the head of the clique linked list for the next level of convolution.
Definition at line 1148 of file convll.c.
References checkBit(), deleteBitSet(), fillSet(), cnode::id, newBitSet(), cnode::next, wholeCliqueConv(), and yankCll().
Referenced by completeConv().
int yankCll (cll_t ** head, cll_t * prev, cll_t ** curr, cll_t ** allCliques, int length)
Removes a clique from within a linked list in order to save it for later printing. This is done so that the cliques are not printed as they are convolved, but rather after all rounds of convolution are complete. Input: a pointer to the head of the current linked list, the clique prior to the one that is to be yanked (NULL if the clique to be yanked is the head), the clique that is to be yanked, a pointer to the head of the list with all cliques that are to be printed, and the length of the current motif. Output: Nothing is returned beyond a success integer, but it alters the current level cll_t, the value of curr, and the linked list of all cliques that are to be printed.
Definition at line 1221 of file convll.c.
References cnode::id, and cnode::next.
Referenced by convolve(), and wholeRoundConv().