FastaSeqIO/fastaSeqIO.c File Reference
#include `fastaSeqIO.h`
#include <stdlib.h>
#include <string.h>
#include <errno.h>
Data Structures
struct sSize_t
Defines
#define BUFFER 100000
#define BIG_BUFFER 1000000
Functions
int printFSeqSubSeq (fSeq_t *seq, int start, int stop)
long measureLine (FILE *INPUT)
long CountFSeqs (FILE *INPUT)
long countLines (FILE *INPUT)
int initAofFSeqs (fSeq_t *aos, int numSeq)
char ** ReadFile (FILE *INPUT, int *n)
fSeq_t * ReadTxtSeqs (FILE *INPUT, int *numberOfSequences)
fSeq_t * ReadFSeqs (FILE *INPUT, int *numberOfSequences)
int FreeFSeqs (fSeq_t *arrayOfSequences, int numberOfSequences)
int WriteFSeqA (FILE *MY_FILE, fSeq_t *arrayOfSequences, int start, int stop)
Define Documentation
#define BIG_BUFFER 1000000
Definition at line 11 of file fastaSeqIO.c.
#define BUFFER 100000
Definition at line 10 of file fastaSeqIO.c.
Function Documentation
long CountFSeqs (FILE * INPUT)
Definition at line 44 of file fastaSeqIO.c.
45 {
46     long start;
47     long count = 0;
48     int myChar;
49     int newLine = 1;
50     start = ftell(INPUT);
51     myChar = fgetc(INPUT);
52     while (myChar != EOF) {
53         if (newLine == 1 && myChar == '>') {
54             count++;
55         }
56         if (myChar == '\n') {
57             newLine = 1;
58         } else {
59             newLine = 0;
60         }
61         myChar = fgetc(INPUT);
62     }
63     fseek(INPUT, start, SEEK_SET);
64     return count;
65 }
long countLines (FILE * INPUT)
Definition at line 69 of file fastaSeqIO.c.
Referenced by ReadFile().
70 {
71     long start;
72     long count = 1;
73     int myChar;
74     int status = 0;
75     start = ftell(INPUT);
76     myChar = fgetc(INPUT);
77     while (myChar != EOF) {
78         if (myChar == '\n') {
79             count++;
80             status = 1;
81         } else {
82             status = 0;
83         }
84         myChar = fgetc(INPUT);
85     }
86     if (status == 1) {
87         count--;
88     }
89     fseek(INPUT, start, SEEK_SET);
90     return count;
91 }
int FreeFSeqs (fSeq_t * arrayOfSequences, int numberOfSequences)
Definition at line 304 of file fastaSeqIO.c.
References fSeq_t::label, and fSeq_t::seq.
Referenced by main().
305 {
306     int i;
307     for (i = 0; i < numberOfSequences; i++) {
308         if (arrayOfSequences[i].label != NULL) {
309             free(arrayOfSequences[i].label);
310         }
311         arrayOfSequences[i].label = NULL;
312 
313         if (arrayOfSequences[i].seq != NULL) {
314             free(arrayOfSequences[i].seq);
315         }
316         arrayOfSequences[i].seq = NULL;
317     }
318     if (arrayOfSequences != NULL) {
319         free(arrayOfSequences);
320     }
321     arrayOfSequences = NULL;
322     return EXIT_SUCCESS;
323 }
int initAofFSeqs (fSeq_t * aos, int numSeq)
Definition at line 94 of file fastaSeqIO.c.
References fSeq_t::label, and fSeq_t::seq.
Referenced by ReadFSeqs(), and ReadTxtSeqs().
95 {
96     int i;
97     for (i = 0; i < numSeq; i++) {
98         aos[i].seq = NULL;
99         aos[i].label = NULL;
100     }
101     return 1;
102 }
long measureLine (FILE * INPUT)
Definition at line 25 of file fastaSeqIO.c.
Referenced by ReadFile().
26 {
27     long start;
28     long count = 0;
29     int myChar;
30     start = ftell(INPUT);
31     myChar = fgetc(INPUT);
32     count++;
33     while (myChar != '\n' && myChar != EOF) {
34         count++;
35         myChar = fgetc(INPUT);
36     }
37     fseek(INPUT, start, SEEK_SET);
38     return count;
39 }
int printFSeqSubSeq (fSeq_t * seq, int start, int stop)
Definition at line 14 of file fastaSeqIO.c.
References fSeq_t::seq.
14                                                  {
15     int i;
16     for(i=start; i<stop; i++){
17         putchar(seq->seq[i]);
18     }
19     return 0;
20 }
char** ReadFile (FILE * INPUT, int * n)
Definition at line 105 of file fastaSeqIO.c.
References countLines(), and measureLine().
Referenced by ReadFSeqs(), readRealData(), and ReadTxtSeqs().
106 {
107     char **buf = NULL;
108     long nl;
109     long tls = 0;
110     int i=0;
111 
112     nl = countLines(INPUT);
113     if( nl == 0){
114         fprintf(stderr, "\nNo sequences! Error!\n\n");
115         fflush(stderr);
116         return NULL;
117     }
118     buf = (char **) malloc ( (int)(nl+1) * sizeof(char *));
119     if ( buf == NULL){
120         fprintf(stderr, "\nMemory Error\n%s\n", strerror(errno));
121         fflush(stderr);
122         exit(0);
123     }
124 
125     //  measure the first line
126     tls = measureLine(INPUT) + 1;
127     if(tls != 0){
128         buf[i] = (char *) malloc ( tls * sizeof(char));
129         if ( buf[i] == NULL){
130             fprintf(stderr, "\nMemory Error\n%s\n", strerror(errno));
131             fflush(stderr);
132             exit(0);
133         }
134     }
135     fgets(buf[i], tls, INPUT);
136     do{
137         if(buf[i][ strlen(buf[i])-1 ] == '\n'){
138             buf[i][ strlen(buf[i])-1 ] = '\0';
139         }
140         tls = measureLine(INPUT) + 1;
141         if(tls != 0){
142             i++;
143             buf[i] = (char *) malloc ( tls * sizeof(char) );
144             if ( buf[i] == NULL){
145                 fprintf(stderr, "\nMemory Error\n%s\n", strerror(errno));
146                 fflush(stderr);
147                 exit(0);
148             }
149         }
150     }while( fgets(buf[i], tls, INPUT) != NULL );
151     free(buf[i]);
152     buf = (char **) realloc ( buf, i * sizeof(char *) );
153     if ( buf == NULL){
154         fprintf(stderr, "\nMemory Error\n%s\n", strerror(errno));
155         fflush(stderr);
156         return NULL;
157     }
158     //  I think that 'i' might actually be the # of lines
159     //  plus one here?  somehow line 131 isn't being freed,
160     //  or at least 2 bytes of it.
161     *n = i;
162     return buf;
163 }
fSeq_t* ReadFSeqs (FILE * INPUT, int * numberOfSequences)
Definition at line 199 of file fastaSeqIO.c.
References initAofFSeqs(), fSeq_t::label, ReadFile(), fSeq_t::seq, sSize_t::size, sSize_t::start, and sSize_t::stop.
Referenced by main().
199                                                {
200     int i,j,k;
201     int nl, ns=0;
202     char **buf = NULL;
203     fSeq_t *aos;
204     sSize_t *ss;
205     sSize_t *ll;
206 
207     buf = ReadFile(INPUT, &nl);
208     if(buf == NULL){
209         return NULL;
210     }
211 
212     //  Count how many sequences we have
213     for( j=0 ; j<nl ; j++){
214         if(buf[j][0] == '>'){
215             ns++;
216         }
217     }
218     ss = (sSize_t *) malloc ( ns * sizeof(sSize_t) );
219     if(ss == NULL){
220         fprintf(stderr, "\nMemory Error\n%s\n", strerror(errno));
221         fflush(stderr);
222         exit(0);
223     }
224     ll = (sSize_t *) malloc ( ns * sizeof(sSize_t) );
225     if(ll == NULL){
226         fprintf(stderr, "\nMemory Error\n%s\n", strerror(errno));
227         fflush(stderr);
228         exit(0);
229     }
230 
231     //  find the first sequence
232     k=0;
233     while( buf[k][0] != '>'){
234         k++;
235     }
236 
237     //  record how large each sequence is
238     i = -1;
239     for( j=k ; j<nl ; j++){
240         if(buf[j][0] == '>'){
241             i++;
242             ll[i].start = j;
243             ll[i].stop = j;
244             ll[i].size = strlen( buf[j] );;
245             ss[i].start = j+1;
246             ss[i].size = 0;
247         }else{
248             ss[i].stop = j;
249             ss[i].size += strlen( buf[j] );;
250         }
251     }
252 
253     aos = (fSeq_t *) malloc ( ns * sizeof(fSeq_t));
254     if( aos == NULL){
255         fprintf(stderr, "\nMemory Error\n%s\n", strerror(errno));
256         fflush(stderr);
257         exit(0);
258     }
259     initAofFSeqs(aos, ns);
260 
261     for ( i=0 ; i<ns ; i++ ){
262         if( ll[i].size > 0 ){
263             aos[i].label = (char *) malloc ( (ll[i].size+1) * sizeof(char) );
264             if( aos[i].label == NULL){
265                 fprintf(stderr, "\nMemory Error\n%s\n", strerror(errno));
266                 fflush(stderr);
267                 exit(0);
268             }
269             aos[i].label[0] = '\0';
270             for ( j=ll[i].start ; j<=ll[i].stop ; j++ ){
271 
272                 //  both instances of strcat here are using
273                 //  .label/.seq's that are NULL and that is
274                 //  throwing a memory error in valgrind
275                 aos[i].label = strcat ( aos[i].label, buf[j] );
276             }
277         }
278         if( ss[i].size > 0 ){
279             aos[i].seq = (char *) malloc ( (ss[i].size+1) * sizeof(char) );
280             if( aos[i].seq == NULL){
281                 fprintf(stderr, "\nMemory Error\n%s\n", strerror(errno));
282                 fflush(stderr);
283                 exit(0);
284             }
285             aos[i].seq[0] = '\0';
286             for ( j=ss[i].start ; j<=ss[i].stop ; j++ ){
287                 aos[i].seq = strcat ( aos[i].seq, buf[j] );
288             }
289         }
290     }
291     free(ll);
292     free(ss);
293 
294     for ( i=0 ; i<nl ; i++ ){
295         free(buf[i]);
296     }
297     free(buf);
298 
299     *numberOfSequences = ns;
300     return aos;
301 }
fSeq_t* ReadTxtSeqs (FILE * INPUT, int * numberOfSequences)
Definition at line 172 of file fastaSeqIO.c.
References initAofFSeqs(), ReadFile(), and fSeq_t::seq.
172                                                  {
173     int i;
174     int nl;
175     char **buf = NULL;
176     fSeq_t *aos;
177 
178     buf = ReadFile(INPUT, &nl);
179     if(buf == NULL){
180         return NULL;
181     }
182     aos = (fSeq_t *) malloc ( nl * sizeof(fSeq_t));
183     if( aos == NULL){
184         fprintf(stderr, "\nMemory Error\n%s\n", strerror(errno));
185         fflush(stderr);
186         exit(0);
187     }
188     initAofFSeqs(aos, nl);
189     for ( i=0 ; i<nl ; i++ ){
190         aos[i].seq = buf[i];
191     }
192     free(buf);
193     *numberOfSequences = nl;
194     return (aos);
195 }
int WriteFSeqA (FILE * MY_FILE, fSeq_t * arrayOfSequences, int start, int stop)
Definition at line 330 of file fastaSeqIO.c.
331 {
332     int i;
333     for (i = start; i <= stop; i++) {
334         fprintf(MY_FILE, "%s\n", arrayOfSequences[i].label);
335         fprintf(MY_FILE, "%s\n", arrayOfSequences[i].seq);
336     }
337     return EXIT_SUCCESS;
338 }