FastaSeqIO/fastaSeqIO.h File Reference
#include <stdio.h>
Data Structures
struct fSeq_t
Functions
int printFSeqSubSeq (fSeq_t *seq, int start, int stop)
long measureLine (FILE *INPUT)
long countLines (FILE *INPUT)
long CountFSeqs (FILE *INPUT)
int initAofFSeqs (fSeq_t *aos, int numSeq)
fSeq_t * ReadFSeqs (FILE *INPUT, int *numberOfSequences)
int FreeFSeqs (fSeq_t *arrayOfSequences, int numberOfSequences)
int WriteFSeqA (FILE *MY_FILE, fSeq_t *arrayOfSequences, int start, int stop)
fSeq_t * ReadTxtSeqs (FILE *INPUT, int *numberOfSequences)
Function Documentation
long CountFSeqs (FILE * INPUT)
Definition at line 44 of file fastaSeqIO.c.
long countLines (FILE * INPUT)
Definition at line 69 of file fastaSeqIO.c.
Referenced by ReadFile().
int FreeFSeqs (fSeq_t * arrayOfSequences, int numberOfSequences)
Definition at line 306 of file fastaSeqIO.c.
References fSeq_t::label, and fSeq_t::seq.
Referenced by main().
int initAofFSeqs (fSeq_t * aos, int numSeq)
Definition at line 94 of file fastaSeqIO.c.
References fSeq_t::label, and fSeq_t::seq.
Referenced by ReadFSeqs(), and ReadTxtSeqs().
long measureLine (FILE * INPUT)
Definition at line 25 of file fastaSeqIO.c.
Referenced by ReadFile().
int printFSeqSubSeq (fSeq_t * seq, int start, int stop)
Definition at line 14 of file fastaSeqIO.c.
References fSeq_t::seq.
fSeq_t* ReadFSeqs (FILE * INPUT, int * numberOfSequences)
Definition at line 199 of file fastaSeqIO.c.
References initAofFSeqs(), fSeq_t::label, ReadFile(), fSeq_t::seq, sSize_t::size, sSize_t::start, and sSize_t::stop.
Referenced by main().
fSeq_t* ReadTxtSeqs (FILE * INPUT, int * numberOfSequences)
Definition at line 172 of file fastaSeqIO.c.
References initAofFSeqs(), ReadFile(), and fSeq_t::seq.
int WriteFSeqA (FILE * MY_FILE, fSeq_t * arrayOfSequences, int start, int stop)
Definition at line 332 of file fastaSeqIO.c.