matrixmap.h File Reference
#include `matdata.h`
#include `matrices.h`
Variables
xx xx xx xx xx xx xx xx xx
struct {
 char * name
 const int(* mat)[MATRIX_SIZE]
} matrix_map []
Detailed Description
This file contains structures and functions for handling scoring matrices.
Definition in file matrixmap.h.
Variable Documentation
const int(* mat)[MATRIX_SIZE]
Definition at line 15 of file matrixmap.h.
Referenced by alignMat(), alignWordsMat_bit(), and main().
struct { ... } matrix_map[]
This data structure maps the names of common matrices to the names of their variables
Referenced by getMatrixByName().
char* name
Definition at line 14 of file matrixmap.h.