patStats.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include `bitSet.h`
#include `convll.h`
#include <time.h>
Functions
unsigned int ** getStatMat (bitGraph_t *bg, int support, int length, int *supportDim, int *lengthDim, int numBlanks, int s, FILE *OUTPUT_FILE)
int cumDMatrix (unsigned int **d, cll_t *cliqs, int currSupport, int currLength, int bgSize, int numSeqs)
int calcStatAllCliqs (unsigned int **d, cll_t *allCliqs, int numWindows)
cll_t * sortByStats (cll_t *allCliqs)
int freeD (unsigned int **d, int supportDim)
Function Documentation
int calcStatAllCliqs (unsigned int ** d, cll_t * allCliqs, int numWindows)
Definition at line 623 of file patStats.c.
References calcStatCliq(), cnode::next, and cnode::stat.
Referenced by main().
int cumDMatrix (unsigned int ** d, cll_t * cliqs, int currSupport, int currLength, int bgSize, int numSeqs)
Definition at line 460 of file patStats.c.
References getLargestLength(), and getLargestSupport().
Referenced by main().
int freeD (unsigned int ** d, int supportDim)
Definition at line 637 of file patStats.c.
Referenced by main().
unsigned int** getStatMat (bitGraph_t * bg, int support, int length, int * supportDim, int * lengthDim, int numBlanks, int s, FILE * OUTPUT_FILE)
Definition at line 289 of file patStats.c.
References bitGraphRowIntersection(), checkBit(), countSet(), deleteBitSet(), bitGraph_t::graph, increaseMem(), measureDiagonal(), newBitSet(), nextBitBitSet(), and bitGraph_t::size.
Referenced by main().
cll_t* sortByStats (cll_t * allCliqs)
This function is used to sort a link to list of cliques by the statistical significance of the motifs found in that linked list.
Definition at line 674 of file patStats.c.
References cnode::id.
Referenced by main().