protAlign.h File Reference
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_vector.h>
#include <gsl/gsl_linalg.h>
#include <gsl/gsl_blas.h>
#include `pdb.h`
#include `bitSet.h`
#include `convll.h`
Data Structures
struct caPoint_t
Functions
caPoint_t * getCaPoint (Pdbentry_ **pdbs, int num, int window, int *numWindows, int *numChains)
bitGraph_t * alignPdbs (caPoint_t *cap, Pdbentry_ **pdbs, int L, double g, int numWindows)
int moveToCentroid (gsl_matrix *m)
int pdb2mat (Pdbentry_ *s, int chainNum, int resStart, int resStop, gsl_matrix *m)
gsl_matrix * sumOuterProd (gsl_matrix *a, gsl_matrix *b)
int gsl_matrix_pretty_fprintf (FILE *fp, const gsl_matrix *a, const char *format)
int rotateMats (gsl_matrix *a, gsl_matrix *b)
double gsl_matrix_rmsd (gsl_matrix *a, gsl_matrix *b)
int outputProtPats (caPoint_t *cap, Pdbentry_ **pdbs, cll_t *allPats, int L, int us, FILE *FH, int format)
Function Documentation
bitGraph_t* alignPdbs (caPoint_t * cap, Pdbentry_ ** pdbs, int L, double g, int numWindows)
Definition at line 26 of file protAlign.c.
References bitGraphSetTrueSym(), gsl_matrix_rmsd(), moveToCentroid(), newBitGraph(), pdb2mat(), caPoint_t::pdbNo, and rotateMats().
Referenced by main().
caPoint_t* getCaPoint (Pdbentry_ ** pdbs, int num, int window, int * numWindows, int * numChains)
Definition at line 69 of file protAlign.c.
References Chain_::Aano, caPoint_t::caNo, caPoint_t::chainNo, Pdbentry_::Chainno, Pdbentry_::Chains, NULL, and caPoint_t::pdbNo.
Referenced by main().
int gsl_matrix_pretty_fprintf (FILE * fp, const gsl_matrix * a, const char * format)
Definition at line 241 of file protAlign.c.
double gsl_matrix_rmsd (gsl_matrix * a, gsl_matrix * b)
Definition at line 310 of file protAlign.c.
Referenced by alignPdbs(), and rmsdCompare().
int moveToCentroid (gsl_matrix * m)
Definition at line 129 of file protAlign.c.
Referenced by alignPdbs(), outputProtPats(), and rmsdCompare().
int outputProtPats (caPoint_t * cap, Pdbentry_ ** pdbs, cll_t * allPats, int L, int us, FILE * FH, int format)
Definition at line 353 of file protAlign.c.
References caPoint_t::caNo, caPoint_t::chainNo, cnode::length, cSet_t::members, moveToCentroid(), cnode::next, NULL, pdb2mat(), caPoint_t::pdbNo, rotateMats(), cnode::set, and cSet_t::size.
Referenced by main().
int pdb2mat (Pdbentry_ * s, int chainNum, int resStart, int resStop, gsl_matrix * m)
Definition at line 164 of file protAlign.c.
References Chain_::Aano, Chain_::Atoms, Pdbentry_::Chainno, Pdbentry_::Chains, and NULL.
Referenced by alignPdbs(), and outputProtPats().
int rotateMats (gsl_matrix * a, gsl_matrix * b)
Definition at line 261 of file protAlign.c.
References NULL, and sumOuterProd().
Referenced by alignPdbs(), outputProtPats(), and rmsdCompare().
gsl_matrix* sumOuterProd (gsl_matrix * a, gsl_matrix * b)
Definition at line 206 of file protAlign.c.
Referenced by rotateMats().