realCompare.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <gsl/gsl_matrix.h>
#include `realIo.h`
#include `bitSet.h`
#include `protAlign.h`
Functions
double rmsdCompare (rdh_t *data, int win1, int win2, int L, double *extraParams)
double generalMatchFactor (rdh_t *data, int win1, int win2, int L, double *extraParams)
double massSpecCompareWElut (rdh_t *data, int win1, int win2, int L, double *extraParams)
bitGraph_t * realComparison (rdh_t *data, int l, double g, int compFunc, double *extraParams)
Variables
double(*)(rdh_t *, int, int, int, double *) getCompFunc (int compFunc)
Detailed Description
This file contains declarations and definitions used for the comparison of real valued data during the comparison phase of Gemoda. The functions declared here are defined in realCompare.c.
Definition in file realCompare.h.
Function Documentation
double generalMatchFactor (rdh_t * data, int win1, int win2, int L, double * extraParams)
This function is used to compute a generalized match factor, which is useful for computing the degree of similarity between mass spectrometry spectra.
Definition at line 111 of file realCompare.c.
References getRdhDim(), getRdhIndexSeqPos(), and rdh_t::seq.
Referenced by getCompFunc().
double massSpecCompareWElut (rdh_t * data, int win1, int win2, int L, double * extraParams)
This function is used to compute the match factor between to mass spectrometry spectra in a similar manner to the previous function; however, this function imposes a penalty for spectra that are separated by large distances in elution time. This function is commonly used by SpecConnect.
Definition at line 174 of file realCompare.c.
References getRdhDim(), getRdhIndexSeqPos(), and rdh_t::seq.
Referenced by getCompFunc().
bitGraph_t* realComparison (rdh_t * data, int l, double g, int compFunc, double * extraParams)
Definition at line 272 of file realCompare.c.
References bitGraphSetTrueSym(), getCompFunc, getRdhIndexSeqPos(), rdh_t::indexSize, initRdhIndex(), newBitGraph(), and rmsdCompare().
Referenced by main().
double rmsdCompare (rdh_t * data, int win1, int win2, int L, double * extraParams)
Calculate the rmsd between two windows, with optional translation and rotation. The input to this function is a real data handler object, two integers that point to the windows within the real data that are to be compared, an integer that specifies the length of the windows, and a pointer to a double precision floating point that can be used to store other parameters as needed. This last parameter is most useful for implementing other comparison functions, without having to make, too many changes to other parts of the code.
This function operates in three stages. First, we compute the centroid of each window and move the second window such that its centroid overlaps with that of the first window. Second, we use rigid body rotation to find the rotational matrix that minimizes the root mean squared deviation between the two windows. Finally, this function returns that minimized RMSD.
Definition at line 31 of file realCompare.c.
References getRdhDim(), getRdhIndexSeqPos(), and rdh_t::seq.
Referenced by getCompFunc(), and realComparison().
Variable Documentation
double(*)(rdh_t*, int, int, int, double*) getCompFunc(int compFunc)
Definition at line 36 of file realCompare.h.
Referenced by findCliqueCentroid(), outputRealPatsWCentroid(), and realComparison().