realIo.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <gsl/gsl_matrix.h>
#include `FastaSeqIO/fastaSeqIO.h`
#include `convll.h`
Data Structures
struct rdh_t
Functions
rdh_t * readRealData (FILE *INPUT)
rdh_t * freeRdh (rdh_t *data)
int initRdhIndex (rdh_t *data, int wordSize, int seqGap)
int getRdhIndexSeqPos (rdh_t *data, int index, int *seq, int *pos)
int getRdhDim (rdh_t *data)
int outputRealPats (rdh_t *data, cll_t *allPats, int L, FILE *OUTPUT_FILE, int **d)
int outputRealPatsWCentroid (rdh_t *data, cll_t *allPats, int L, FILE *OUTPUT_FILE, double *extraParams, int compFunc)
Function Documentation
rdh_t* freeRdh (rdh_t * data)
This function returns a null pointer after freeing the memory associated with a real data holder object. The function takes one parameter: a pointer to the real data holder, data.
Definition at line 396 of file realIo.c.
References rdh_t::indexToPos, rdh_t::indexToSeq, rdh_t::label, rdh_t::offsetToIndex, rdh_t::seq, and rdh_t::size.
Referenced by main().
int getRdhDim (rdh_t * data)
This function returns an integer equal to the dimensions of the data stored in a real data holder object. The function takes one parameter: a pointer to the real data holder, data.
Definition at line 447 of file realIo.c.
References rdh_t::seq.
Referenced by generalMatchFactor(), getRdhValue(), massSpecCompareWElut(), printRdhSeq(), rmsdCompare(), and setRdhValue().
int getRdhIndexSeqPos (rdh_t * data, int index, int * seq, int * pos)
This function is used to access and change the sequence and position values, given an index. The function takes four parameters: a pointer to the real data holder, data, an integer index, a pointer integer seq, and a pointer integer pos.
Definition at line 544 of file realIo.c.
References rdh_t::indexSize, rdh_t::indexToPos, and rdh_t::indexToSeq.
Referenced by generalMatchFactor(), makeAlternateCentroid(), massSpecCompareWElut(), outputRealPats(), outputRealPatsWCentroid(), realComparison(), and rmsdCompare().
int initRdhIndex (rdh_t * data, int wordSize, int seqGap)
This function is used to initialize the two indices inside a real data holder. The function takes as its input three parameters a pointer to the real data holder, data, the size of the words to be compared during the comparison stage wordSize, and an integer seqGap, which is used to place empty data between unique sequences, such that we do not convolve from one sequence into another during the convolution stage.
Definition at line 307 of file realIo.c.
References getRdhSeqLength(), rdh_t::indexSize, rdh_t::indexToPos, rdh_t::indexToSeq, rdh_t::offsetToIndex, and rdh_t::size.
Referenced by realComparison().
int outputRealPats (rdh_t * data, cll_t * allPats, int L, FILE * OUTPUT_FILE, int ** d)
This function is used to print out motifs discovered by Gemoda in an attractive fashion. The function takes five parameters: a pointer to a real data holder object data; a pointer to a linked list of motifs allPats; an integer which is Gemoda's input parameter L; and a pointer to a file handle to which output is printed OUTPUT_FILE.
Definition at line 904 of file realIo.c.
References getRdhIndexSeqPos(), cnode::length, cSet_t::members, cnode::next, rdh_t::seq, cnode::set, cSet_t::size, and cnode::stat.
Referenced by main().
int outputRealPatsWCentroid (rdh_t * data, cll_t * allPats, int L, FILE * OUTPUT_FILE, double * extraParams, int compFunc)
This function is used to output real valued patterns in a format such that they are centered on a particular centroid.
Definition at line 1068 of file realIo.c.
References findCliqueCentroid(), getCompFunc, getRdhIndexSeqPos(), cnode::length, makeAlternateCentroid(), cSet_t::members, cnode::next, cnode::set, and cSet_t::size.
Referenced by main().
rdh_t* readRealData (FILE * INPUT)
This function is used to read in a fasta formatted file containing real value data and store the entire thing and a real data holder object. The function takes one parameter: a pointer to a file handle, which is where the data are read from INPUT;
Definition at line 850 of file realIo.c.
References checkRealDataFormat(), parseRealData(), and ReadFile().
Referenced by main().