realIo.c File Reference
#include `realIo.h`
#include `realCompare.h`
#include `patStats.h`
Functions
wordToDouble (char *s, int begin, int end)
int countFields (char *s, char sep)
int checkRealDataFormat (char **buf, int nl, char sep, int *numSeq_p, int *dim_p)
int countTotalFields (char **buf, int nl, char sep)
rdh_t * initRdh (int x)
int getRdhSeqLength (rdh_t *data, int seqNo)
int initRdhIndex (rdh_t *data, int wordSize, int seqGap)
rdh_t * freeRdh (rdh_t *data)
int getRdhDim (rdh_t *data)
int setRdhLabel (rdh_t *data, int seqNo, char *s)
int setRdhValue (rdh_t *data, int seqNo, int posNo, int dimNo, double val)
int setRdhIndex (rdh_t *data, int seqNo, int posNo, int index)
int getRdhIndexSeqPos (rdh_t *data, int index, int *seq, int *pos)
double getRdhValue (rdh_t *data, int seqNo, int posNo, int dimNo)
char * getRdhLabel (rdh_t *data, int seqNo)
int printRdhSeq (rdh_t *data, int seqNo, FILE *FH)
int setRdhColFromString (rdh_t *data, int seqNo, int colNo, char *s, char sep)
int initRdhGslMat (rdh_t *data, int seqNo, int x, int y)
int pushOnRdhSeq (rdh_t *data, char **buf, int startLine, int dim, char sep)
rdh_t * parseRealData (char **buf, int nl, char sep, int numSeq, int dim)
rdh_t * readRealData (FILE *INPUT)
int outputRealPats (rdh_t *data, cll_t *allPats, int L, FILE *OUTPUT_FILE, int **d)
int findCliqueCentroid (rdh_t *data, cll_t *curCliq, int L, int compFunc, double *extraParams, int *candidates)
int makeAlternateCentroid (rdh_t *data, cll_t *curCliq, int *candidates)
int outputRealPatsWCentroid (rdh_t *data, cll_t *allPats, int L, FILE *OUTPUT_FILE, double *extraParams, int compFunc)
Detailed Description
This file defines functions that are used for the parsing of user supplied data in the real valued implementation of Gemoda.
Definition in file realIo.c.
Function Documentation
int checkRealDataFormat (char ** buf, int nl, char sep, int * numSeq_p, int * dim_p)
Check that each sequence has the same dimensionality and that, within a sequence, each dimension has the same number of entries. Note: this routine alters *nunSeq_p and *dim_p! Also, you must call this routine before calling parseRealData. Otherwise, parseRealData is garunteed to die if the data turn out to be ill-formatted.
Definition at line 163 of file realIo.c.
References countFields().
Referenced by readRealData().
164 {
165   int i;
166   int thisDim = 0;
167   int status = 1;
168   int width;
169   int fieldCount = 0;       // number of positions in a single sequence
170   int numSeq = 0;       // number of sequences 
171   int dim = 0;          // The dimensionality of the sequences
172 
173   // NOTE this is not checking the dimensionality of the last sequence...
174   // that's bad.  We can fix that though.
175   // Check the dimensionality of each sequence
176   for (i = 0; i < nl; i++)
177     {
178       if (buf[i][0] == '>')
179     {
180 
181       // If this is only the second sequence we've seen,
182       // record the dimensionality of the first sequence
183       // as the dim to insist upon from here on out
184       if (numSeq == 1)
185         {
186           dim = thisDim;
187 
188           // For other sequences, we need to check to make sure
189           // that they've got the same dimensions as previous
190           // sequences
191         }
192       else if (numSeq > 1)
193         {
194 
195           // If the dimensions are wrong, quit with status=0
196           if (thisDim != dim)
197         {
198           status = 0;
199           break;
200         }
201         }
202       numSeq++;
203       width = 0;
204       thisDim = 0;
205     }
206       else
207     {
208 
209       // Field count can be different for each sequence but
210       // must be the same for each dimension in a single sequence
211       fieldCount = countFields (buf[i], sep);
212 
213       // If this is the first row of this sequence,
214       // then store the number of fields
215       if (thisDim == 0)
216         {
217           width = fieldCount;
218 
219           // If it's not the first row, make sure it has the
220           // same number of fields as previous rows in this
221           // sequence
222         }
223       else
224         {
225           if (fieldCount != width)
226         {
227           status = 0;
228           break;
229         }
230         }
231       thisDim++;
232     }
233     }
234 
235   // Pass back the numSeq and dim
236   *numSeq_p = numSeq;
237   *dim_p = thisDim;
238   return status;
239 }
int countFields (char * s, char sep)
Count the number of fields (delimited by 'sep') in a single string. I was going to use strsep in string.h for this; however, I don't like that it changes the input string, which makes free-ing the string later more tricky. Ignores consecutive seperators.
Definition at line 90 of file realIo.c.
References wordToDouble().
Referenced by checkRealDataFormat(), countTotalFields(), and pushOnRdhSeq().
91 {
92   int i;
93   int begin = 0;
94   int end = 0;
95   int status = 0;       // 0 = in sep, 1 = in word
96   int fieldCount = 0;
97   double val;
98   if (s == NULL)
99     {
100       fprintf (stderr, "Passed NULL string to countFields -- error!");
101       fflush (stderr);
102       exit (0);
103     }
104 
105   // Loop over the length of the string
106   for (i = 0; i < strlen (s); i++)
107     {
108 
109       // The previous state was space
110       if (status == 0)
111     {
112 
113       // We hit a word
114       if (s[i] != sep)
115         {
116           begin = i;
117           status = 1;
118         }
119       else
120         {           // We hit more space
121           continue;
122         }
123     }
124       else
125     {           // The previous state was word
126       if (s[i] != sep)
127         {
128           continue;
129         }
130       else
131         {           // We hit a space
132           end = i - 1;
133           status = 0;
134 
135           // being and end now delimit a word,
136           // turn that word into a double
137           val = wordToDouble (s, begin, end);
138           fieldCount++;
139         }
140     }
141     }
142 
143   // At the end, if we were in a word, we have
144   // one more field
145   if (status == 1)
146     {               // We're in a word
147       val = wordToDouble (s, begin, strlen (s));
148       fieldCount++;
149     }
150   return fieldCount;
151 }
int countTotalFields (char ** buf, int nl, char sep)
Count the number of fields in each sequence and return the sum of these.
Definition at line 246 of file realIo.c.
References countFields().
Referenced by parseRealData().
247 {
248   int i = 0;
249   int totalFields = 0;
250   int seqNo = 0;
251   while (i < nl)
252     {
253 
254       // Hit a new sequence
255       if (buf[i][0] == '>')
256     {
257       seqNo++;
258 
259       // Assume that the sequence has at least
260       // one row (should have called checkRealDataFormat!
261       // and that each row has the same number of fields
262       totalFields += countFields (buf[i + 1], sep);
263     }
264       i++;
265     }
266   return totalFields;
267 }
int findCliqueCentroid (rdh_t * data, cll_t * curCliq, int L, int compFunc, double * extraParams, int * candidates)
This function is used to find the centroid of a clique. That is, to find the center of mass.
Definition at line 1096 of file realIo.c.
References getCompFunc, cSet_t::members, cnode::set, and cSet_t::size.
Referenced by outputRealPatsWCentroid().
1098 {
1099   double (*comparisonFunc) (rdh_t *, int, int, int, double *) = NULL;
1100   int i = 0, j = 0, indmin = -1, counter = 0;
1101   double sim = 0, min = 0, flagmin = 0;
1102   double *cliqueAdjMat = NULL;
1103   cliqueAdjMat = (double *) malloc (curCliq->set->size * sizeof (double));
1104   if (cliqueAdjMat == NULL)
1105     {
1106       fprintf (stderr, "\nMemory Error\n%s\n", strerror (errno));
1107       fflush (stderr);
1108       exit (0);
1109     }
1110   for (i = 0; i < curCliq->set->size; i++)
1111     {
1112       cliqueAdjMat[i] = 0;
1113     }
1114 
1115   // We'll accumulate our comparison function values... except here
1116   // we're really assuming that we're using a match factor, with
1117   // value less than one, so that we can subtract it from one to
1118   // get a distance, and then find the centroid by identifying the
1119   // node with the smallest cumulative Euclidean distance to all
1120   // nodes.  
1121   // Note that we only need to compare each unique pair, and can apply
1122   // the results from each comparison to each member of the pair,
1123   // hence the somewhat odd indices of initiation for the for loops.
1124   comparisonFunc = getCompFunc (compFunc);
1125   for (i = 0; i < curCliq->set->size; i++)
1126     {
1127       for (j = i + 1; j < curCliq->set->size; j++)
1128     {
1129       sim =
1130         comparisonFunc (data, curCliq->set->members[i],
1131                 curCliq->set->members[j], L, extraParams);
1132 
1133       // printf("i = %d, j = %d, L = %d, extra = %lf, sim =
1134       // %lf\n",i,j,L,extraParams[0],sim);
1135       cliqueAdjMat[i] += pow (1 - sim, 2);
1136       cliqueAdjMat[j] += pow (1 - sim, 2);
1137     }
1138     }
1139 
1140   // Now we find the minimum Euclidean distance.
1141   min = cliqueAdjMat[0];
1142   indmin = 0;
1143   for (i = 1; i < curCliq->set->size; i++)
1144     {
1145 
1146       // printf("index %d product = %lf\n",i,cliqueAdjMat[i]);
1147       if (cliqueAdjMat[i] < min)
1148     {
1149       indmin = i;
1150       min = cliqueAdjMat[i];
1151       flagmin = 0;
1152     }
1153       else if (cliqueAdjMat[i] == min)
1154     {
1155       flagmin = 1;
1156     }
1157     }
1158 
1159   // If we had a duplicate on the minimum, we locate all duplicates.
1160   if (flagmin == 1)
1161     {
1162       counter = 0;
1163       for (i = 0; i < curCliq->set->size; i++)
1164     {
1165       if (cliqueAdjMat[i] == min)
1166         {
1167           counter++;
1168           candidates[counter] = i;
1169         }
1170     }
1171 
1172       // Store the number of candidates at the array's beginning
1173       candidates[0] = counter;
1174       free (cliqueAdjMat);
1175       return (-1);
1176     }
1177   else
1178     {
1179       free (cliqueAdjMat);
1180       return (indmin);
1181     }
1182 }
rdh_t* freeRdh (rdh_t * data)
This function returns a null pointer after freeing the memory associated with a real data holder object. The function takes one parameter: a pointer to the real data holder, data.
Definition at line 462 of file realIo.c.
References rdh_t::indexToPos, rdh_t::indexToSeq, rdh_t::label, rdh_t::offsetToIndex, and rdh_t::seq.
Referenced by main().
463 {
464   int i;
465   if (data != NULL)
466     {
467       if (data->indexToPos != NULL)
468     {
469       free (data->indexToPos);
470       data->indexToPos = NULL;
471     }
472       if (data->indexToSeq != NULL)
473     {
474       free (data->indexToSeq);
475       data->indexToSeq = NULL;
476     }
477       if (data->offsetToIndex != NULL)
478     {
479       for (i = 0; i < data->size; i++)
480         {
481           free (data->offsetToIndex[i]);
482           data->offsetToIndex[i] = NULL;
483         }
484       free (data->offsetToIndex);
485       data->offsetToIndex = NULL;
486     }
487       for (i = 0; i < data->size; i++)
488     {
489       if (data->seq[i] != NULL)
490         {
491           gsl_matrix_free (data->seq[i]);
492           data->seq[i] = NULL;
493         }
494       if (data->label[i] != NULL)
495         {
496           free (data->label[i]);
497           data->label[i] = NULL;
498         }
499     }
500       if (data->seq != NULL)
501     {
502       free (data->seq);
503       data->seq = NULL;
504     }
505       if (data->label != NULL)
506     {
507       free (data->label);
508       data->label = NULL;
509     }
510       free (data);
511       data = NULL;
512     }
513   return data;
514 }
int getRdhDim (rdh_t * data)
This function returns an integer equal to the dimensions of the data stored in a real data holder object. The function takes one parameter: a pointer to the real data holder, data.
Definition at line 524 of file realIo.c.
References rdh_t::seq.
Referenced by generalMatchFactor(), getRdhValue(), massSpecCompareWElut(), printRdhSeq(), rmsdCompare(), and setRdhValue().
525 {
526   if (data == NULL || data->seq == NULL || data->seq[0] == NULL)
527     {
528       fprintf (stderr, "Passed bad data to getRdhSeqLength -- error!");
529       fflush (stderr);
530       exit (0);
531     }
532   return data->seq[0]->size2;
533 }
int getRdhIndexSeqPos (rdh_t * data, int index, int * seq, int * pos)
This function is used to access and change the sequence and position values, given an index. The function takes four parameters: a pointer to the real data holder, data, an integer index, a pointer integer seq, and a pointer integer pos.
Definition at line 633 of file realIo.c.
References rdh_t::indexSize, rdh_t::indexToPos, and rdh_t::indexToSeq.
Referenced by generalMatchFactor(), makeAlternateCentroid(), massSpecCompareWElut(), outputRealPats(), outputRealPatsWCentroid(), realComparison(), and rmsdCompare().
634 {
635   if (data == NULL || data->indexToSeq == NULL || data->indexToPos == NULL
636       || index > data->indexSize)
637     {
638       fprintf (stderr, "Passed bad data to getRdhIndexSeqPos -- error!");
639       fflush (stderr);
640       exit (0);
641     }
642 
643   /*
644      printf("Setting index %d -> %d, %d\n", index, seqNo, posNo);
645    */
646   /*
647      fflush(stdout);
648    */
649   *seq = data->indexToSeq[index];
650   *pos = data->indexToPos[index];
651   return 0;
652 }
char* getRdhLabel (rdh_t * data, int seqNo)
This function is used to retrieve the label of a particular sequence in a real data holder object. The function takes two parameters: a pointer to the real data holder data; and an integer which is the sequence number to be accessed seqNo. The function returns a pointer to a string, which is the label for that sequence.
Definition at line 689 of file realIo.c.
References rdh_t::label.
Referenced by printRdhSeq().
690 {
691   if (data == NULL || data->label == NULL || data->label[seqNo] == NULL)
692     {
693       fprintf (stderr, "Passed bad data to getRdhLabel -- error!");
694       fflush (stderr);
695       exit (0);
696     }
697   return data->label[seqNo];
698 }
int getRdhSeqLength (rdh_t * data, int seqNo)
This function returns an integer that is equal to the sequence length of a particular sequence within the real data holder object. The function takes two parameters: a pointer to the real data holder, data, and the index of the sequence for which we need to know the length, seqNo.
Definition at line 331 of file realIo.c.
References rdh_t::seq.
Referenced by getRdhValue(), initRdhIndex(), printRdhSeq(), and setRdhValue().
332 {
333   if (data == NULL || data->seq == NULL || data->seq[seqNo] == NULL)
334     {
335       fprintf (stderr, "Passed bad data to getRdhSeqLength -- error!");
336       fflush (stderr);
337       exit (0);
338     }
339   return data->seq[seqNo]->size1;
340 }
double getRdhValue (rdh_t * data, int seqNo, int posNo, int dimNo)
This function is used to retrieve the value of a particular dimension, position, and sequence. The function takes four parameters: a pointer to the real data holder data; an integer which is the sequence number to be accessed seqNo; an integer that is the position number to be accessed posNo; and an integer that is the dimension to be accessed dimNo.
Definition at line 666 of file realIo.c.
References getRdhDim(), getRdhSeqLength(), and rdh_t::seq.
Referenced by printRdhSeq().
667 {
668   if (data == NULL || data->seq == NULL || data->seq[seqNo] == NULL
669       || posNo > getRdhSeqLength (data, seqNo) || dimNo > getRdhDim (data))
670     {
671       fprintf (stderr, "Passed bad data to getRdhValue -- error!");
672       fflush (stderr);
673       exit (0);
674     }
675   return gsl_matrix_get (data->seq[seqNo], posNo, dimNo);
676 }
rdh_t* initRdh (int x)
This function initializes a real data holder object. The function takes as its input a size x which is the number of sequences that will be stored in the object. The function returns a pointer to the object, which has been allocated the correct amount of memory.
Definition at line 277 of file realIo.c.
References rdh_t::indexSize, rdh_t::indexToPos, rdh_t::indexToSeq, rdh_t::label, rdh_t::seq, and rdh_t::size.
Referenced by parseRealData().
278 {
279   int i;
280   rdh_t *data = NULL;
281 
282   // Allocate space for our structure
283   data = (rdh_t *) malloc (sizeof (rdh_t));
284   if (data == NULL)
285     {
286       fprintf (stderr, "\nMemory Error\n%s\n", strerror (errno));
287       fflush (stderr);
288       exit (0);
289     }
290   data->size = x;
291 
292   // Index has to be initialized later, once
293   // we know the word size.
294   data->indexSize = 0;
295   data->indexToSeq = NULL;
296   data->indexToPos = NULL;
297 
298   /*
299      data->indexSize = y;
300    */
301   data->label = (char **) malloc (data->size * sizeof (char *));
302   if (data->label == NULL)
303     {
304       fprintf (stderr, "\nMemory Error\n%s\n", strerror (errno));
305       fflush (stderr);
306       exit (0);
307     }
308   data->seq = (gsl_matrix **) malloc (data->size * sizeof (gsl_matrix *));
309   if (data->seq == NULL)
310     {
311       fprintf (stderr, "\nMemory Error\n%s\n", strerror (errno));
312       fflush (stderr);
313       exit (0);
314     }
315   for (i = 0; i < data->size; i++)
316     {
317       data->label[i] = NULL;
318       data->seq[i] = NULL;
319     }
320   return data;
321 }
int initRdhGslMat (rdh_t * data, int seqNo, int x, int y)
This function is used to initialize the memory for the matrix in which the real value to data are stored. To store these data, we use the GNU scientific library. The function takes four parameters: a pointer to the real data holder data; an integer, which is the sequence number to be set seqNo; an integer, which is the first dimension of the matrix size x; and an integer, which is the second dimension of the matrix size y;
Definition at line 829 of file realIo.c.
References rdh_t::seq.
Referenced by pushOnRdhSeq().
830 {
831   data->seq[seqNo] = gsl_matrix_alloc (x, y);
832   if (data->seq[seqNo] == NULL)
833     {
834       return 0;
835     }
836   else
837     {
838       return 1;
839     }
840 }
int initRdhIndex (rdh_t * data, int wordSize, int seqGap)
This function is used to initialize the two indices inside a real data holder. The function takes as its input three parameters a pointer to the real data holder, data, the size of the words to be compared during the comparison stage wordSize, and an integer seqGap, which is used to place empty data between unique sequences, such that we do not convolve from one sequence into another during the convolution stage.
Definition at line 358 of file realIo.c.
References getRdhSeqLength(), rdh_t::indexSize, rdh_t::indexToPos, rdh_t::indexToSeq, rdh_t::offsetToIndex, and rdh_t::size.
Referenced by realComparison().
359 {
360   int i, j, k;
361   int numWindows = 0;
362   int thisNumWindows;
363   int numSeq;
364   int seqLen = 0;
365 
366   // The number of sequences
367   numSeq = data->size;
368 
369   // Allocate offsetToIndex's outer structure
370   data->offsetToIndex = (int **) malloc (numSeq * sizeof (int *));
371   if (data->offsetToIndex == NULL)
372     {
373       fprintf (stderr, "\nMemory Error\n%s\n", strerror (errno));
374       fflush (stderr);
375       exit (0);
376     }
377 
378   // For each sequence
379   for (i = 0; i < numSeq; i++)
380     {
381 
382       // How many windows are in this sequence
383       seqLen = getRdhSeqLength (data, i);
384       numWindows += seqLen - wordSize + 1;
385 
386       // And also use this to further allocate offsetToIndex
387       data->offsetToIndex[i] =
388     (int *) malloc ((seqLen - wordSize + 1) * sizeof (int));
389       if (data->offsetToIndex[i] == NULL)
390     {
391       fprintf (stderr, "\nMemory Error\n%s\n", strerror (errno));
392       fflush (stderr);
393       exit (0);
394     }
395     }
396 
397   // One index for each word plus seqGap between each sequence
398   // and a gap at the end
399   data->indexSize = numWindows + numSeq * seqGap;
400 
401   // Allocate indexToSeq 
402   // NOTE that it should be size of int, not int *... I think we got
403   // fortunate in the previous revision because they are the same
404   // size
405   data->indexToSeq = (int *) malloc (data->indexSize * sizeof (int));
406   if (data->indexToSeq == NULL)
407     {
408       fprintf (stderr, "\nMemory Error\n%s\n", strerror (errno));
409       fflush (stderr);
410       exit (0);
411     }
412 
413   // Allocate indexToPos 
414   // See above for int vs. int* argument.
415   data->indexToPos = (int *) malloc (data->indexSize * sizeof (int));
416   if (data->indexToPos == NULL)
417     {
418       fprintf (stderr, "\nMemory Error\n%s\n", strerror (errno));
419       fflush (stderr);
420       exit (0);
421     }
422 
423   // Fill in the values
424   k = 0;
425   for (i = 0; i < numSeq; i++)
426     {
427 
428       // How many windows are in this sequence?
429       thisNumWindows = getRdhSeqLength (data, i) - wordSize + 1;
430 
431       // For each window, make an entry in the indexToSeq
432       // and indexToPos and offsetToIndex
433       for (j = 0; j < thisNumWindows; j++)
434     {
435       data->indexToSeq[k] = i;
436       data->indexToPos[k] = j;
437       data->offsetToIndex[i][j] = k;
438       k++;
439     }
440 
441       // Add gaps between sequences in the index.
442       // Usually seqGap is just 1;
443       for (j = 0; j < seqGap; j++)
444     {
445 
446       // -1 means no sequence and no position
447       data->indexToSeq[k] = -1;
448       data->indexToPos[k] = -1;
449       k++;
450     }
451     }
452   return 0;
453 }
int makeAlternateCentroid (rdh_t * data, cll_t * curCliq, int * candidates)
This function is used to choose an alternate centroid for a given clique. In order to make the centroid decision slightly less dependent on input order, we decide to choose from the tied candidates the one whose relative position in the sequence is highest. There is no basis in theory for this, it is done so that a consistent choice is made. Only rarely will two spectra be tied for being a centroid and have the same sequence number. In that case, we pretty much have to default to the sequence number, which is what would be done without this function. Note that now though we are less sensitive to the order of input of the sequences, we are now more sensitive to the context surrounding a given spectrum. That is, if it is put in the beginning of the sequence, it is more likely to be chosen. This choice can only be justified insofar as if multiple choices are tied, then they are the same cumulative distance to the clique, and so *any* should be allowed to be chosen equally. There should be little difference in terms of tangible results. This just makes the semantics consistent.
Definition at line 1202 of file realIo.c.
References getRdhIndexSeqPos(), cSet_t::members, and cnode::set.
Referenced by outputRealPatsWCentroid().
1203 {
1204   int indmin, min, i;
1205   int curSeq, curPos;
1206   int numCandidates = candidates[0];
1207   indmin = candidates[1];
1208   getRdhIndexSeqPos (data, curCliq->set->members[indmin], &curSeq, &curPos);
1209   min = curPos;
1210 
1211   // We use less-than-or-equal here because we're starting at 1, 
1212   // so we want 1 to end.  The length of candidates is one more than
1213   // the maxSup, so we know we can reach candidates[maxSup] without
1214   // a segfault.
1215   for (i = 2; i <= numCandidates; i++)
1216     {
1217       getRdhIndexSeqPos (data, curCliq->set->members[candidates[i]], &curSeq,
1218              &curPos);
1219       if (curPos < min)
1220     {
1221       indmin = candidates[i];
1222       min = curPos;
1223     }
1224     }
1225   return (indmin);
1226 }
int outputRealPats (rdh_t * data, cll_t * allPats, int L, FILE * OUTPUT_FILE, int ** d)
This function is used to print out motifs discovered by Gemoda in an attractive fashion. The function takes five parameters: a pointer to a real data holder object data; a pointer to a linked list of motifs allPats; an integer which is Gemoda's input parameter L; and a pointer to a file handle to which output is printed OUTPUT_FILE.
Definition at line 1046 of file realIo.c.
References getRdhIndexSeqPos(), cnode::length, cSet_t::members, cnode::next, rdh_t::seq, cnode::set, cSet_t::size, and cnode::stat.
Referenced by main().
1048 {
1049   int i, j, pos1;
1050   int curSeq, curPos;
1051   cll_t *curCliq = NULL;
1052   curCliq = allPats;
1053   i = 0;
1054   while (curCliq != NULL)
1055     {
1056       fprintf (OUTPUT_FILE, "pattern %d:\tlen=%d\tsup=%d\t", i,
1057            curCliq->length + L, curCliq->set->size);
1058       if (d != NULL)
1059     {
1060       fprintf (OUTPUT_FILE, "\tsignif=%le\n", curCliq->stat);
1061     }
1062       else
1063     {
1064       fprintf (OUTPUT_FILE, "\n");
1065     }
1066       for (j = 0; j < curCliq->set->size; j++)
1067     {
1068       pos1 = curCliq->set->members[j];
1069       getRdhIndexSeqPos (data, pos1, &curSeq, &curPos);
1070       fprintf (OUTPUT_FILE, "   %d\t%d\t", curSeq, curPos);
1071       fprintf (OUTPUT_FILE, "%lf\t",
1072            gsl_matrix_get (data->seq[curSeq], curPos, 0));
1073 
1074       /*
1075          for(k=curPos ; k<curPos+curCliq->length+L ; k++){ fprintf(OUTPUT_FILE, "%c",
1076          mySequences[curSeq].seq[k]); } 
1077        */
1078       fprintf (OUTPUT_FILE, "\n");
1079     }
1080       fprintf (OUTPUT_FILE, "\n\n");
1081       curCliq = curCliq->next;
1082       i++;
1083     }
1084   return 0;
1085 }
int outputRealPatsWCentroid (rdh_t * data, cll_t * allPats, int L, FILE * OUTPUT_FILE, double * extraParams, int compFunc)
This function is used to output real valued patterns in a format such that they are centered on a particular centroid.
Definition at line 1233 of file realIo.c.
References findCliqueCentroid(), getCompFunc, getRdhIndexSeqPos(), cnode::length, makeAlternateCentroid(), cSet_t::members, cnode::next, cnode::set, and cSet_t::size.
Referenced by main().
1236 {
1237   int i, j, k, pos1, centroid;
1238   int curSeq, curPos;
1239   int maxSup = 0;
1240   cll_t *curCliq = NULL;
1241   double mfToCentroid = 0;
1242   double (*comparisonFunc) (rdh_t *, int, int, int, double *) = NULL;
1243   int *candidates = NULL;
1244   curCliq = allPats;
1245   while (curCliq != NULL)
1246     {
1247       if (curCliq->set->size > maxSup)
1248     {
1249       maxSup = curCliq->set->size;
1250     }
1251       curCliq = curCliq->next;
1252     }
1253   candidates = (int *) malloc ((maxSup + 1) * sizeof (int));
1254   if (candidates == NULL)
1255     {
1256       fprintf (stderr, "\nMemory Error\n%s\n", strerror (errno));
1257       fflush (stderr);
1258       exit (0);
1259     }
1260   for (i = 0; i <= maxSup; i++)
1261     {
1262       candidates[i] = 0;
1263     }
1264   comparisonFunc = getCompFunc (compFunc);
1265   curCliq = allPats;
1266   i = 0;
1267   while (curCliq != NULL)
1268     {
1269       fprintf (OUTPUT_FILE, "pattern %d:\tlen=%d\tsup=%d\n", i,
1270            curCliq->length + L, curCliq->set->size);
1271       centroid =
1272     findCliqueCentroid (data, curCliq, L, compFunc, extraParams,
1273                 candidates);
1274       if (centroid < 0)
1275     {
1276       centroid = makeAlternateCentroid (data, curCliq, candidates);
1277 
1278       // fprintf(OUTPUT_FILE, "WARNING: No single node in"
1279       // " cluster has non-zero similarity to all other\n nodes"
1280       // " in cluster; centroid set to first node.\n");
1281       // centroid = 0;
1282     }
1283       for (j = 0; j < curCliq->set->size; j++)
1284     {
1285       pos1 = curCliq->set->members[j];
1286       getRdhIndexSeqPos (data, pos1, &curSeq, &curPos);
1287       fprintf (OUTPUT_FILE, "   %d\t%d\t", curSeq, curPos);
1288 
1289       // fprintf(OUTPUT_FILE, "%lf\t",
1290       // gsl_matrix_get(data->seq[curSeq],curPos,0));
1291       mfToCentroid =
1292         comparisonFunc (data, curCliq->set->members[j],
1293                 curCliq->set->members[centroid], L, extraParams);
1294       fprintf (OUTPUT_FILE, "%lf\t", mfToCentroid);
1295 
1296       /*
1297          for(k=curPos ; k<curPos+curCliq->length+L ; k++){ fprintf(OUTPUT_FILE, "%c",
1298          mySequences[curSeq].seq[k]); } 
1299        */
1300       fprintf (OUTPUT_FILE, "\n");
1301     }
1302       fprintf (OUTPUT_FILE, "\n\n");
1303       curCliq = curCliq->next;
1304       i++;
1305       for (k = 0; k <= maxSup; k++)
1306     {
1307       candidates[k] = 0;
1308     }
1309     }
1310   free (candidates);
1311   return 0;
1312 }
rdh_t* parseRealData (char ** buf, int nl, char sep, int numSeq, int dim)
This function is used to parse a single line of a fastA formatted input buffer containing real valued data. The function takes
parameters: a pointer to an array of pointers to characters, which stores the sequences that we will read from buf; an integer, which is the line in the buffer on which we should start nl; a single character, which is used to delimit the input data sep; an integer which is the number of the sequence that we are currently reading in numSeq; an integer that is the dimensionality of the input data dim;
Definition at line 933 of file realIo.c.
References countTotalFields(), initRdh(), and pushOnRdhSeq().
Referenced by readRealData().
934 {
935   int i;
936   int seqNo = -1;
937   int totalNumFields;
938   rdh_t *data = NULL;
939   totalNumFields = countTotalFields (buf, nl, sep);
940 
941   /*
942      data = initRdh(numSeq, totalNumFields + numSeq - 1);
943    */
944   data = initRdh (numSeq);
945 
946   // We're going to add an empty index between
947   // windows that correspond to different 
948   // sequences
949 
950   // Fast forward to the first sequence
951   i = 0;
952   while (i < nl)
953     {
954 
955       // Hit a new sequence
956       if (buf[i][0] == '>')
957     {
958       seqNo++;      // Note that seqNo started at -1!
959       pushOnRdhSeq (data, buf, i, dim, sep);
960       i += dim + 1;
961     }
962       else
963     {
964       i++;
965     }
966     }
967 
968   /*
969      printRdhSeq(data, 0, stdout);
970    */
971   return data;
972 }
int printRdhSeq (rdh_t * data, int seqNo, FILE * FH)
This function is used to print out a real valued data sequence in a pretty manner. The function takes three parameters: a pointer to the real data holder data; an integer which is the sequence to be printed out seqNo; and a pointer to a file handle which is where the output will be printed FH.
Definition at line 710 of file realIo.c.
References getRdhDim(), getRdhLabel(), getRdhSeqLength(), and getRdhValue().
711 {
712   int i, j;
713   int len;
714   int dim;
715   len = getRdhSeqLength (data, seqNo);
716   dim = getRdhDim (data);
717   fprintf (FH, "%s\n", getRdhLabel (data, seqNo));
718   for (i = 0; i < len; i++)
719     {
720       for (j = 0; j < dim; j++)
721     {
722       fprintf (FH, "%3.1f ", getRdhValue (data, seqNo, i, j));
723     }
724       fprintf (FH, "\n");
725     }
726   return 0;
727 }
int pushOnRdhSeq (rdh_t * data, char ** buf, int startLine, int dim, char sep)
This function is used to fill in a real data holder structure as we are reading in the sequences. Notably, this routine uses a few static variables, so it can only be called once and should not be used to alter the real data holder structure later. The function takes five parameters: a pointer to the real data holder data; a pointer to an array of pointers to characters, which stores the sequences that we will read from buf; an integer, which is the line in the buffer on which we should start startLine; an integer that is the dimensionality of the input data dim; a single character, which is used to delimit the input data sep;
Definition at line 863 of file realIo.c.
References countFields(), initRdhGslMat(), setRdhColFromString(), and setRdhLabel().
Referenced by parseRealData().
864 {
865   int i, j, k;
866   int numFields;
867 
868   // NOTE THAT THESE ARE STATIC VARIABLES!!!!!
869   // That is, they retain their last value on
870   // each call to this function!
871   static int seqNo = 0;
872 
873   /*
874      static int indexNo=0;
875    */
876   i = startLine;
877 
878   // Assume that the sequence has at least
879   // one row (should have called checkRealDataFormat!
880   numFields = countFields (buf[i + 1], sep);
881 
882   // Initialize the gsl_matrix object for this 
883   // sequence in 'data'
884   // 
885   // NOTE THAT WE STORE THE TRANSPOSE OF WHAT'S IN
886   // THE INPUT FILE -- x,y = position x, dimension y
887   initRdhGslMat (data, seqNo, numFields, dim);
888 
889   // Set the sequence label
890   setRdhLabel (data, seqNo, buf[i]);
891 
892   // Read in 'dim' rows
893   for (j = i + 1, k = 0; j < i + 1 + dim; j++, k++)
894     {
895 
896       /*
897          printf("%d\n", countFields(buf[j], sep));
898        */
899 
900       // Set the k-th dimension of this sequence
901       // STILL NOTE THE TRANSPOSE!
902       setRdhColFromString (data, seqNo, k, buf[j], sep);
903     }
904 
905   /*
906      for ( l=0 ; l<numFields ; l++ ){ setRdhIndex(data, seqNo, l, indexNo); indexNo++;
907      } 
908    */
909   seqNo++;
910 
911   // Augment indexNo once more to have a -1 between each sequence!
912   /*
913      indexNo++; 
914    */
915   return 0;
916 }
rdh_t* readRealData (FILE * INPUT)
This function is used to read in a fasta formatted file containing real value data and store the entire thing and a real data holder object. The function takes one parameter: a pointer to a file handle, which is where the data are read from INPUT;
Definition at line 983 of file realIo.c.
References checkRealDataFormat(), parseRealData(), and ReadFile().
Referenced by main().
984 {
985   char **buf = NULL;
986   int nl;
987   int i;
988   char sep = ' ';
989   int numSeq = 0;
990   int dimensions = 0;
991   int status = 1;
992   rdh_t *data = NULL;
993 
994   // Read the entire INPUT file and put it's
995   // contents into 'buf'.  This function also
996   // alters the contents of the location pointed
997   // to by &nl.  Now nl is the number of lines
998   // in the file (or the size of the buff array.
999   buf = ReadFile (INPUT, &nl);
1000   if (buf == NULL)
1001     {
1002       return NULL;
1003     }
1004   status = checkRealDataFormat (buf, nl, sep, &numSeq, &dimensions);
1005   if (numSeq <= 0 || dimensions <= 0 || status == 0)
1006     {
1007       fprintf (stderr,
1008            "Data file is poorly formatted or no sequences read!\n");
1009       fprintf (stderr,
1010            "Each sequence needs to be the same dimensionality!  QUITTING!\n");
1011       fprintf (stderr, "numSeq = %d, dimensions = %d, status = %d\n", numSeq,
1012            dimensions, status);
1013       exit (EXIT_FAILURE);
1014     }
1015 
1016   // From here on, we assume that the sequence file is well-formatted
1017   // to make the code more simple.
1018   data = parseRealData (buf, nl, sep, numSeq, dimensions);
1019 
1020   // Free up our buffer
1021   for (i = 0; i < nl; i++)
1022     {
1023       if (buf[i] != NULL)
1024     {
1025       free (buf[i]);
1026     }
1027     }
1028   if (buf != NULL)
1029     {
1030       free (buf);
1031     }
1032   return data;
1033 }
int setRdhColFromString (rdh_t * data, int seqNo, int colNo, char * s, char sep)
This function is used to fill in the values of a sequence in a real data holder object by reading them straight from a string, which is assumed to be a series of floating-point values separated by some particular character. The function takes five parameters: a pointer to the real data holder data; an integer, which is the sequence number to be set seqNo; an integer representing the dimension of the sequence which is to be set colNo; a pointer to the string holding the floating-point values s; a character, which separates the floating-point values in the string sep;
Definition at line 744 of file realIo.c.
References rdh_t::seq, setRdhValue(), and wordToDouble().
Referenced by pushOnRdhSeq().
745 {
746   int i;
747   int begin = 0;
748   int end = 0;
749   int status = 0;       // 0 = in sep, 1 = in word
750   int fieldCount = 0;
751   double val;
752 
753   // Make sure the string is not null and
754   // the rdh_t gsl_matrix array is not null
755   // and the selected gsl_matrix is not null
756   if (s == NULL || data->seq == NULL || data->seq[seqNo] == NULL)
757     {
758       fprintf (stderr, "Passed bad data to setRdhColFromString -- error!");
759       fflush (stderr);
760       exit (0);
761     }
762 
763   // Loop over the length of the string
764   for (i = 0; i < strlen (s); i++)
765     {
766 
767       // The previous state was space
768       if (status == 0)
769     {
770 
771       // We hit a word
772       if (s[i] != sep)
773         {
774           begin = i;
775           status = 1;
776         }
777       else
778         {           // We hit more space
779           continue;
780         }
781     }
782       else
783     {           // The previous state was word
784       if (s[i] != sep)
785         {
786           continue;
787         }
788       else
789         {           // We hit a space
790           end = i - 1;
791           status = 0;
792           val = wordToDouble (s, begin, end);
793 
794           // Go to the gsl_matrix object data->seq[seqNo]
795           // and set the (fieldCount, colNo) = val;
796           setRdhValue (data, seqNo, fieldCount, colNo, val);
797           fieldCount++;
798         }
799     }
800     }
801 
802   // At the end, if we were in a word, we have
803   // one more field
804   if (status == 1)
805     {               // We're in a word
806       val = wordToDouble (s, begin, strlen (s));
807 
808       // Added in, MPS 5/3/05 ---
809       // And don't forget to set the RdhValue!
810       setRdhValue (data, seqNo, fieldCount, colNo, val);
811       fieldCount++;
812     }
813   return fieldCount;
814 }
int setRdhIndex (rdh_t * data, int seqNo, int posNo, int index)
This function is used to fill in entries in the indices of the real data holder. The function takes four parameters: a pointer to the real data holder, data, an integer specifying the sequence number seqNo, an integer specifying the position number within the sequence posNo, and an integer specifying what the index for this sequence number and position number should be index.
Definition at line 600 of file realIo.c.
References rdh_t::indexSize, rdh_t::indexToPos, and rdh_t::indexToSeq.
601 {
602   if (data == NULL || data->indexToSeq == NULL || data->indexToPos == NULL
603       || index > data->indexSize)
604     {
605       fprintf (stderr, "Passed bad data to getRdhValue -- error!");
606       fflush (stderr);
607       exit (0);
608     }
609 
610   /*
611      printf("Setting index %d -> %d, %d\n", index, seqNo, posNo);
612    */
613   /*
614      fflush(stdout);
615    */
616   data->indexToSeq[index] = seqNo;
617   data->indexToPos[index] = posNo;
618   return 0;
619 }
int setRdhLabel (rdh_t * data, int seqNo, char * s)
This function will label a sequence within a real data holder object with a particular string. The function takes two parameters: a pointer to the real data holder, data, an integer seqNo, and a pointer to a string s.
Definition at line 543 of file realIo.c.
References rdh_t::label, and rdh_t::seq.
Referenced by pushOnRdhSeq().
544 {
545   if (data->seq == NULL || data->label == NULL)
546     {
547       fprintf (stderr, "Passed bad data to setRdhLabel -- error!");
548       fflush (stderr);
549       exit (0);
550     }
551   data->label[seqNo] = strdup (s);
552   if (data->label[seqNo] == NULL)
553     {
554       fprintf (stderr, "\nMemory Error allocating label!\n%s\n",
555            strerror (errno));
556       fflush (stderr);
557       exit (0);
558     }
559   return 0;
560 }
int setRdhValue (rdh_t * data, int seqNo, int posNo, int dimNo, double val)
This function will set a particular dimension at a particular position within a specified sequence to a user supplied value. The function takes five parameters: a pointer to the real data holder, data, an integer seqNo which is the sequence which needs its value set, two integers that specify the position number and the dimension number that needs to be set, and finally a double precision floating point number which is the value to which the the data should be set.
Definition at line 575 of file realIo.c.
References getRdhDim(), getRdhSeqLength(), and rdh_t::seq.
Referenced by setRdhColFromString().
576 {
577   if (data == NULL || data->seq == NULL || data->seq[seqNo] == NULL
578       || posNo > getRdhSeqLength (data, seqNo) || dimNo > getRdhDim (data))
579     {
580       fprintf (stderr, "Passed bad data to setRdhValue -- error!");
581       fflush (stderr);
582       exit (0);
583     }
584   gsl_matrix_set (data->seq[seqNo], posNo, dimNo, val);
585   return 0;
586 }
wordToDouble (char * s, int begin, int end)
Turn the substring of s starting at char s[begin] and ending at s[end] int a double. INPUT: a string s, integer begin, and integer end. OUTPUT: a double. NOTE: Throws an error and dies if there's a problem making the double from the substring. No room for ill-formated data files. double
Definition at line 30 of file realIo.c.
Referenced by countFields(), and setRdhColFromString().
31 {
32   char *str = NULL;
33   char *endptr;
34   double val;
35   int size;
36   int memsize;
37 
38   // Check for a sane substring
39   if (end - begin <= 0)
40     {
41       fprintf (stderr, "\nInvalid argument to wordToDouble!\n");
42       fflush (stderr);
43       exit (0);
44     }
45 
46   // Get the required string size
47   memsize = end - begin + 2;    // An extra space in mem for null-termination
48   size = end - begin + 1;
49 
50   // Get memory for a temporary string
51   str = (char *) malloc (memsize * sizeof (char));
52   if (str == NULL)
53     {
54       fprintf (stderr, "\nMemory Error\n%s\n", strerror (errno));
55       fflush (stderr);
56       exit (0);
57     }
58 
59   // Make sure the string ends with a null char
60   str[size] = '\0';
61 
62   // Copy the word into str
63   str = strncpy (str, s + begin, size);
64 
65   // Set endptr to str as initial value
66   endptr = str;
67   val = strtod (str, &endptr);
68 
69   // endptr should point to the last char
70   // used in the conversion if strtod worked
71   if (val == 0 && endptr == str)
72     {
73       fprintf (stderr, "\nError making double from string: %s\n", str);
74       fflush (stderr);
75       exit (0);
76     }
77   free (str);
78   return val;
79 }